<?php
require_once '../includes/db.php';
require_once '../includes/session.php';
check_login();

// Access control: Allow admins, instructors, officers, and higher ranks
if(!in_array($_SESSION['role'], ['admin', 'instructor', 'officer', '1cl', '2cl', 'commandant'])){
    die('Access Denied. You do not have permission to add grades.');
}

// Fetch all cadets for the dropdown
$sql = "SELECT u.id, p.first_name, p.last_name, p.platoon FROM users u JOIN cadet_profiles p ON u.id = p.user_id WHERE u.role IN ('cadet', 'basic_cadet') ORDER BY p.platoon, p.last_name, p.first_name";
$cadets = [];
if($result = mysqli_query($link, $sql)){
    while($row = mysqli_fetch_assoc($result)){
        $cadets[] = $row;
    }
}

// Get statistics for dashboard
$total_grades_sql = "SELECT COUNT(*) as total FROM grades";
$total_grades_result = mysqli_query($link, $total_grades_sql);
$total_grades = mysqli_fetch_assoc($total_grades_result)['total'] ?? 0;

$recent_grades_sql = "SELECT COUNT(*) as total FROM grades WHERE created_at >= DATE_SUB(NOW(), INTERVAL 7 DAY)";
$recent_grades_result = mysqli_query($link, $recent_grades_sql);
$recent_grades = mysqli_fetch_assoc($recent_grades_result)['total'] ?? 0;

$total_cadets = count($cadets);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Grade - ROTC Management System</title>
    <link rel="stylesheet" href="../css/tactical-theme.css">
    <link rel="stylesheet" href="../css/dashboard-unified.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>

<body data-role="<?php echo $_SESSION['role']; ?>">
    <div class="dashboard-container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <div class="sidebar-header">
                <div class="logo">
                    <div class="logo-icon"><i class="fas fa-plus-circle"></i></div>
                    <span>Add Grade</span>
                </div>
            </div>
            
            <nav class="sidebar-nav">
                <div class="nav-menu">
                    <!-- Navigation will be generated by JavaScript -->
                </div>
            </nav>
        </aside>

        <!-- Main Content -->
        <main class="main-content">
            <!-- Header -->
            <header class="header">
                <div class="header-left">
                    <button class="sidebar-toggle">
                        <i class="fas fa-bars"></i>
                    </button>
                    <h1 class="page-title">Add Grade</h1>
                </div>
                
                <div class="header-right">
                    <div class="header-actions">
                        <button class="action-btn" onclick="bulkGradeMode()" title="Bulk Grade Entry">
                            <i class="fas fa-list"></i>
                        </button>
                        <button class="action-btn" onclick="importGrades()" title="Import Grades">
                            <i class="fas fa-file-import"></i>
                        </button>
                        <div class="user-menu">
                            <div class="user-avatar">
                                <i class="fas fa-user"></i>
                                <span class="user-name"><?php echo htmlspecialchars($_SESSION['full_name']); ?></span>
                                <i class="fas fa-chevron-down"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <!-- Content Area -->
            <div class="content-area">
                <!-- Statistics -->
                <div class="stats-grid">
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-graduation-cap"></i>
                        </div>
                        <div class="stat-content">
                            <div class="stat-number"><?php echo $total_grades; ?></div>
                            <div class="stat-label">Total Grades</div>
                        </div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-calendar-week"></i>
                        </div>
                        <div class="stat-content">
                            <div class="stat-number"><?php echo $recent_grades; ?></div>
                            <div class="stat-label">This Week</div>
                        </div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        <div class="stat-content">
                            <div class="stat-number"><?php echo $total_cadets; ?></div>
                            <div class="stat-label">Total Cadets</div>
                        </div>
                    </div>
                </div>

                <?php if(isset($_GET['message'])): ?>
                    <div class="alert <?php echo ($_GET['status'] == 'success') ? 'alert-success' : 'alert-danger'; ?>">
                        <i class="fas <?php echo ($_GET['status'] == 'success') ? 'fa-check-circle' : 'fa-exclamation-triangle'; ?>"></i>
                        <?php echo htmlspecialchars($_GET['message']); ?>
                    </div>
                <?php endif; ?>

                <!-- Grade Entry Form -->
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-plus-circle"></i> Add New Grade</h3>
                        <div class="card-actions">
                            <span class="badge badge-primary">Grade Entry</span>
                        </div>
                    </div>
                    <div class="card-content">
                        <form action="process_grade.php" method="post" class="grade-form" id="gradeForm">
                            <div class="form-grid">
                                <div class="form-group">
                                    <label for="cadet_id">
                                        <i class="fas fa-user-graduate"></i> Select Cadet
                                    </label>
                                    <select name="cadet_id" id="cadet_id" class="form-control" required>
                                        <option value="">-- Select a Cadet --</option>
                                        <?php 
                                        $current_platoon = '';
                                        foreach($cadets as $cadet): 
                                            if($cadet['platoon'] != $current_platoon) {
                                                if($current_platoon != '') echo '</optgroup>';
                                                echo '<optgroup label="Platoon ' . htmlspecialchars($cadet['platoon']) . '">';
                                                $current_platoon = $cadet['platoon'];
                                            }
                                        ?>
                                            <option value="<?php echo $cadet['id']; ?>">
                                                <?php echo htmlspecialchars($cadet['last_name'] . ', ' . $cadet['first_name']); ?>
                                            </option>
                                        <?php endforeach; ?>
                                        <?php if($current_platoon != '') echo '</optgroup>'; ?>
                                    </select>
                                    <div class="form-help">Search by typing cadet name</div>
                                </div>

                                <div class="form-group">
                                    <label for="event_name">
                                        <i class="fas fa-clipboard-list"></i> Event/Assessment Name
                                    </label>
                                    <input type="text" name="event_name" id="event_name" class="form-control" 
                                           placeholder="e.g., Midterm Exam, Physical Fitness Test" 
                                           list="event_suggestions" required>
                                    <datalist id="event_suggestions">
                                        <option value="Midterm Exam">
                                        <option value="Final Exam">
                                        <option value="Physical Fitness Test">
                                        <option value="Drill Competition">
                                        <option value="Leadership Assessment">
                                        <option value="Academic Project">
                                        <option value="Field Training Exercise">
                                    </datalist>
                                </div>

                                <div class="form-group">
                                    <label for="grade_type">
                                        <i class="fas fa-tags"></i> Grade Type
                                    </label>
                                    <select name="grade_type" id="grade_type" class="form-control" required>
                                        <option value="">-- Select Type --</option>
                                        <option value="academic">📚 Academic</option>
                                        <option value="physical">💪 Physical Fitness</option>
                                        <option value="leadership">⭐ Leadership</option>
                                        <option value="drill">🎯 Drill & Ceremony</option>
                                        <option value="field_training">🏕️ Field Training</option>
                                        <option value="other">📋 Other</option>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="grade">
                                        <i class="fas fa-award"></i> Grade/Score
                                    </label>
                                    <div class="grade-input-group">
                                        <input type="text" name="grade" id="grade" class="form-control" 
                                               placeholder="Enter grade or score" required>
                                        <select name="grade_scale" id="grade_scale" class="form-control grade-scale">
                                            <option value="percentage">% (0-100)</option>
                                            <option value="letter">Letter (A-F)</option>
                                            <option value="points">Points</option>
                                            <option value="pass_fail">Pass/Fail</option>
                                        </select>
                                    </div>
                                    <div class="form-help">Enter the grade according to the selected scale</div>
                                </div>

                                <div class="form-group">
                                    <label for="max_score">
                                        <i class="fas fa-bullseye"></i> Maximum Score (Optional)
                                    </label>
                                    <input type="number" name="max_score" id="max_score" class="form-control" 
                                           placeholder="e.g., 100" min="1">
                                    <div class="form-help">Leave empty if not applicable</div>
                                </div>

                                <div class="form-group">
                                    <label for="weight">
                                        <i class="fas fa-balance-scale"></i> Weight/Importance
                                    </label>
                                    <select name="weight" id="weight" class="form-control">
                                        <option value="1">Normal (1x)</option>
                                        <option value="1.5">Important (1.5x)</option>
                                        <option value="2">Major (2x)</option>
                                        <option value="0.5">Minor (0.5x)</option>
                                    </select>
                                </div>

                                <div class="form-group full-width">
                                    <label for="comments">
                                        <i class="fas fa-comment-alt"></i> Comments & Feedback
                                    </label>
                                    <textarea name="comments" id="comments" class="form-control" 
                                              rows="4" placeholder="Provide detailed feedback, areas for improvement, or commendations..."></textarea>
                                    <div class="form-help">Constructive feedback helps cadets improve their performance</div>
                                </div>

                                <div class="form-group">
                                    <label for="date_assessed">
                                        <i class="fas fa-calendar"></i> Assessment Date
                                    </label>
                                    <input type="date" name="date_assessed" id="date_assessed" class="form-control" 
                                           value="<?php echo date('Y-m-d'); ?>" required>
                                </div>

                                <div class="form-group">
                                    <label for="notify_cadet">
                                        <i class="fas fa-bell"></i> Notification
                                    </label>
                                    <div class="checkbox-group">
                                        <label class="checkbox-label">
                                            <input type="checkbox" name="notify_cadet" id="notify_cadet" checked>
                                            <span class="checkmark"></span>
                                            Notify cadet of new grade
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-actions">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fas fa-plus-circle"></i> Add Grade
                                </button>
                                <button type="button" class="btn btn-outline" onclick="previewGrade()">
                                    <i class="fas fa-eye"></i> Preview
                                </button>
                                <button type="button" class="btn btn-secondary" onclick="resetForm()">
                                    <i class="fas fa-undo"></i> Reset
                                </button>
                            </div>
                        </form>
                    </div>
                </div>

                <!-- Quick Actions -->
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-bolt"></i> Quick Actions</h3>
                    </div>
                    <div class="card-content">
                        <div class="quick-actions">
                            <button class="action-card" onclick="bulkGradeMode()">
                                <i class="fas fa-list"></i>
                                <span>Bulk Grade Entry</span>
                                <small>Add grades for multiple cadets</small>
                            </button>
                            <button class="action-card" onclick="viewGrades()">
                                <i class="fas fa-chart-line"></i>
                                <span>View All Grades</span>
                                <small>Review existing grades</small>
                            </button>
                            <button class="action-card" onclick="gradeAnalytics()">
                                <i class="fas fa-analytics"></i>
                                <span>Grade Analytics</span>
                                <small>Performance insights</small>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <script src="../js/dashboard-unified.js"></script>

    <script>
        // Make cadet select searchable
        document.getElementById('cadet_id').addEventListener('input', function() {
            // This would typically integrate with a search library like Select2
        });

        // Grade scale change handler
        document.getElementById('grade_scale').addEventListener('change', function() {
            const gradeInput = document.getElementById('grade');
            const scale = this.value;
            
            switch(scale) {
                case 'percentage':
                    gradeInput.placeholder = 'Enter percentage (0-100)';
                    gradeInput.type = 'number';
                    gradeInput.min = '0';
                    gradeInput.max = '100';
                    break;
                case 'letter':
                    gradeInput.placeholder = 'Enter letter grade (A, B, C, D, F)';
                    gradeInput.type = 'text';
                    gradeInput.removeAttribute('min');
                    gradeInput.removeAttribute('max');
                    break;
                case 'points':
                    gradeInput.placeholder = 'Enter points earned';
                    gradeInput.type = 'number';
                    gradeInput.min = '0';
                    gradeInput.removeAttribute('max');
                    break;
                case 'pass_fail':
                    gradeInput.placeholder = 'Enter Pass or Fail';
                    gradeInput.type = 'text';
                    gradeInput.removeAttribute('min');
                    gradeInput.removeAttribute('max');
                    break;
            }
        });

        // Form validation
        document.getElementById('gradeForm').addEventListener('submit', function(e) {
            const grade = document.getElementById('grade').value.trim();
            const scale = document.getElementById('grade_scale').value;
            
            // Validate grade based on scale
            if (scale === 'percentage') {
                const numGrade = parseFloat(grade);
                if (isNaN(numGrade) || numGrade < 0 || numGrade > 100) {
                    e.preventDefault();
                    alert('Please enter a valid percentage between 0 and 100.');
                    return;
                }
            } else if (scale === 'letter') {
                const validGrades = ['A', 'B', 'C', 'D', 'F', 'A+', 'A-', 'B+', 'B-', 'C+', 'C-', 'D+', 'D-'];
                if (!validGrades.includes(grade.toUpperCase())) {
                    e.preventDefault();
                    alert('Please enter a valid letter grade (A, B, C, D, F with optional + or -).');
                    return;
                }
            } else if (scale === 'pass_fail') {
                const validValues = ['PASS', 'FAIL', 'P', 'F'];
                if (!validValues.includes(grade.toUpperCase())) {
                    e.preventDefault();
                    alert('Please enter Pass/Fail or P/F.');
                    return;
                }
            }
        });

        // Preview function
        function previewGrade() {
            const cadetSelect = document.getElementById('cadet_id');
            const cadetName = cadetSelect.options[cadetSelect.selectedIndex].text;
            const eventName = document.getElementById('event_name').value;
            const grade = document.getElementById('grade').value;
            const scale = document.getElementById('grade_scale').value;
            const comments = document.getElementById('comments').value;
            
            if (!cadetSelect.value || !eventName || !grade) {
                alert('Please fill in the required fields to preview.');
                return;
            }
            
            const preview = `
                Cadet: ${cadetName}
                Event: ${eventName}
                Grade: ${grade} (${scale})
                Comments: ${comments || 'None'}
            `;
            
            alert(preview);
        }

        // Reset form
        function resetForm() {
            if (confirm('Are you sure you want to reset the form?')) {
                document.getElementById('gradeForm').reset();
                document.getElementById('date_assessed').value = '<?php echo date('Y-m-d'); ?>';
            }
        }

        // Quick action functions
        function bulkGradeMode() {
            alert('Bulk grade entry feature coming soon!');
        }

        function viewGrades() {
            window.location.href = 'manage_grades.php';
        }

        function gradeAnalytics() {
            alert('Grade analytics feature coming soon!');
        }

        function importGrades() {
            alert('Grade import feature coming soon!');
        }

        // Auto-save draft functionality
        setInterval(function() {
            const formData = {
                cadet_id: document.getElementById('cadet_id').value,
                event_name: document.getElementById('event_name').value,
                grade: document.getElementById('grade').value,
                comments: document.getElementById('comments').value
            };
            
            if (formData.cadet_id || formData.event_name || formData.grade) {
                localStorage.setItem('grade_draft', JSON.stringify(formData));
            }
        }, 30000);

        // Load draft on page load
        window.addEventListener('load', function() {
            const draft = localStorage.getItem('grade_draft');
            if (draft) {
                const draftData = JSON.parse(draft);
                if (confirm('A draft was found. Would you like to restore it?')) {
                    document.getElementById('cadet_id').value = draftData.cadet_id;
                    document.getElementById('event_name').value = draftData.event_name;
                    document.getElementById('grade').value = draftData.grade;
                    document.getElementById('comments').value = draftData.comments;
                }
            }
        });
    </script>

    <style>
        .grade-form {
            margin: 0;
        }

        .form-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 1.5rem;
            margin-bottom: 2rem;
        }

        .form-group.full-width {
            grid-column: 1 / -1;
        }

        .form-group {
            display: flex;
            flex-direction: column;
            gap: 0.5rem;
        }

        .form-group label {
            font-weight: 600;
            color: var(--text-secondary);
            font-size: 0.875rem;
            display: flex;
            align-items: center;
            gap: 0.5rem;
        }

        .form-control {
            padding: 0.75rem;
            border: 1px solid var(--border-primary);
            border-radius: 6px;
            background: var(--bg-primary);
            color: var(--text-primary);
            font-size: 0.875rem;
            transition: all 0.2s ease;
        }

        .form-control:focus {
            outline: none;
            border-color: var(--primary);
            box-shadow: 0 0 0 3px rgba(var(--primary-rgb), 0.1);
        }

        .grade-input-group {
            display: flex;
            gap: 0.5rem;
        }

        .grade-input-group .form-control {
            flex: 1;
        }

        .grade-scale {
            flex: 0 0 140px;
        }

        .form-help {
            font-size: 0.75rem;
            color: var(--text-secondary);
            margin-top: 0.25rem;
        }

        .checkbox-group {
            display: flex;
            flex-direction: column;
            gap: 0.5rem;
        }

        .checkbox-label {
            display: flex;
            align-items: center;
            gap: 0.5rem;
            cursor: pointer;
            font-weight: normal;
        }

        .checkbox-label input[type="checkbox"] {
            margin: 0;
        }

        .form-actions {
            display: flex;
            gap: 1rem;
            justify-content: flex-start;
            padding-top: 1rem;
            border-top: 1px solid var(--border-primary);
        }

        .quick-actions {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
        }

        .action-card {
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 0.5rem;
            padding: 1.5rem;
            border: 1px solid var(--border-primary);
            border-radius: 8px;
            background: var(--bg-primary);
            color: var(--text-primary);
            text-decoration: none;
            transition: all 0.2s ease;
            cursor: pointer;
        }

        .action-card:hover {
            border-color: var(--primary);
            background: var(--bg-secondary);
            transform: translateY(-2px);
        }

        .action-card i {
            font-size: 2rem;
            color: var(--primary);
        }

        .action-card span {
            font-weight: 600;
            font-size: 1rem;
        }

        .action-card small {
            color: var(--text-secondary);
            font-size: 0.75rem;
            text-align: center;
        }

        @media (max-width: 768px) {
            .form-grid {
                grid-template-columns: 1fr;
            }
            
            .form-actions {
                flex-direction: column;
            }
            
            .grade-input-group {
                flex-direction: column;
            }
            
            .grade-scale {
                flex: 1;
            }
            
            .quick-actions {
                grid-template-columns: 1fr;
            }
        }
    </style>
</body>
</html>
