<?php
require_once '../includes/db.php';
require_once '../includes/session.php';
require_once '../includes/SecurityLogger.php';
check_login();

// Access control: Allow admins, instructors, officers, and higher ranks
if(!in_array($_SESSION['role'], ['admin', 'instructor', 'officer', '1cl', '2cl', 'commandant'])){
    SecurityLogger::log('UNAUTHORIZED_ACCESS', 'HIGH', 'Unauthorized attempt to access grade management', [
        'user_id' => $_SESSION['user_id'] ?? null,
        'username' => $_SESSION['username'] ?? 'anonymous',
        'role' => $_SESSION['role'] ?? 'none',
        'ip_address' => $_SERVER['REMOTE_ADDR'],
        'user_agent' => $_SERVER['HTTP_USER_AGENT']
    ]);
    die('Access Denied. You do not have permission to manage grades.');
}

// Log successful access to grade management
SecurityLogger::log('GRADE_MANAGEMENT_ACCESS', 'LOW', 'User accessed grade management system', [
    'user_id' => $_SESSION['user_id'],
    'username' => $_SESSION['username'],
    'role' => $_SESSION['role'],
    'ip_address' => $_SERVER['REMOTE_ADDR']
]);

// Fetch all cadets with their platoon information
$sql = "SELECT u.id, p.first_name, p.last_name, p.platoon FROM users u JOIN cadet_profiles p ON u.id = p.user_id WHERE u.role IN ('cadet', 'basic_cadet') ORDER BY p.platoon, p.last_name, p.first_name";
$cadets = [];
if($result = mysqli_query($link, $sql)){
    while($row = mysqli_fetch_assoc($result)){
        $cadets[] = $row;
    }
}

// Fetch existing grades for display
$grades_sql = "SELECT g.*, u.id as user_id, p.first_name, p.last_name, p.platoon 
               FROM grades g 
               JOIN users u ON g.cadet_id = u.id 
               JOIN cadet_profiles p ON u.id = p.user_id 
               ORDER BY g.created_at DESC LIMIT 50";
$grades = [];
if($result = mysqli_query($link, $grades_sql)){
    while($row = mysqli_fetch_assoc($result)){
        $grades[] = $row;
    }
}

// Get statistics for dashboard
$total_grades_sql = "SELECT COUNT(*) as total FROM grades";
$total_grades_result = mysqli_query($link, $total_grades_sql);
$total_grades = mysqli_fetch_assoc($total_grades_result)['total'] ?? 0;

$recent_grades_sql = "SELECT COUNT(*) as total FROM grades WHERE created_at >= DATE_SUB(NOW(), INTERVAL 7 DAY)";
$recent_grades_result = mysqli_query($link, $recent_grades_sql);
$recent_grades = mysqli_fetch_assoc($recent_grades_result)['total'] ?? 0;

$avg_grade_sql = "SELECT AVG(CAST(grade AS DECIMAL(5,2))) as avg_grade FROM grades WHERE grade REGEXP '^[0-9]+\\.?[0-9]*$'";
$avg_grade_result = mysqli_query($link, $avg_grade_sql);
$avg_grade = round(mysqli_fetch_assoc($avg_grade_result)['avg_grade'] ?? 0, 1);

$total_cadets = count($cadets);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manage Grades - ROTC Management System</title>
    <link rel="stylesheet" href="../css/tactical-theme.css">
    <link rel="stylesheet" href="../css/dashboard-unified.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>

<body data-role="<?php echo $_SESSION['role']; ?>">
    <div class="dashboard-container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <div class="sidebar-header">
                <div class="logo">
                    <div class="logo-icon"><i class="fas fa-chart-line"></i></div>
                    <span>Manage Grades</span>
                </div>
            </div>
            
            <nav class="sidebar-nav">
                <div class="nav-menu">
                    <!-- Navigation will be generated by JavaScript -->
                </div>
            </nav>
        </aside>

        <!-- Main Content -->
        <main class="main-content">
            <!-- Header -->
            <header class="header">
                <div class="header-left">
                    <button class="sidebar-toggle">
                        <i class="fas fa-bars"></i>
                    </button>
                    <h1 class="page-title">Manage Grades</h1>
                </div>
                
                <div class="header-right">
                    <div class="header-actions">
                        <div class="search-container">
                            <input type="text" id="searchGrades" placeholder="Search grades..." class="search-input">
                            <i class="fas fa-search search-icon"></i>
                        </div>
                        <button class="action-btn" onclick="addNewGrade()" title="Add New Grade">
                            <i class="fas fa-plus"></i>
                        </button>
                        <button class="action-btn" onclick="exportGrades()" title="Export Grades">
                            <i class="fas fa-download"></i>
                        </button>
                        <button class="action-btn" onclick="gradeAnalytics()" title="Grade Analytics">
                            <i class="fas fa-chart-bar"></i>
                        </button>
                        <div class="user-menu">
                            <div class="user-avatar">
                                <i class="fas fa-user"></i>
                                <span class="user-name"><?php echo htmlspecialchars($_SESSION['full_name']); ?></span>
                                <i class="fas fa-chevron-down"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <!-- Content Area -->
            <div class="content-area">
                <!-- Statistics -->
                <div class="stats-grid">
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-graduation-cap"></i>
                        </div>
                        <div class="stat-content">
                            <div class="stat-number"><?php echo $total_grades; ?></div>
                            <div class="stat-label">Total Grades</div>
                        </div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-calendar-week"></i>
                        </div>
                        <div class="stat-content">
                            <div class="stat-number"><?php echo $recent_grades; ?></div>
                            <div class="stat-label">This Week</div>
                        </div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-chart-line"></i>
                        </div>
                        <div class="stat-content">
                            <div class="stat-number"><?php echo $avg_grade; ?>%</div>
                            <div class="stat-label">Average Grade</div>
                        </div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        <div class="stat-content">
                            <div class="stat-number"><?php echo $total_cadets; ?></div>
                            <div class="stat-label">Total Cadets</div>
                        </div>
                    </div>
                </div>

                <?php if(isset($_GET['message'])): ?>
                    <div class="alert <?php echo ($_GET['status'] == 'success') ? 'alert-success' : 'alert-danger'; ?>">
                        <i class="fas <?php echo ($_GET['status'] == 'success') ? 'fa-check-circle' : 'fa-exclamation-triangle'; ?>"></i>
                        <?php echo htmlspecialchars($_GET['message']); ?>
                    </div>
                <?php endif; ?>

                <!-- Filters and Actions -->
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-filter"></i> Filters & Actions</h3>
                        <div class="card-actions">
                            <button class="btn btn-outline" onclick="resetFilters()">
                                <i class="fas fa-undo"></i> Reset
                            </button>
                        </div>
                    </div>
                    <div class="card-content">
                        <div class="filter-grid">
                            <div class="filter-group">
                                <label for="filterPlatoon">
                                    <i class="fas fa-users"></i> Platoon
                                </label>
                                <select id="filterPlatoon" class="form-control">
                                    <option value="">All Platoons</option>
                                    <option value="1">Platoon 1</option>
                                    <option value="2">Platoon 2</option>
                                    <option value="3">Platoon 3</option>
                                    <option value="4">Platoon 4</option>
                                </select>
                            </div>
                            <div class="filter-group">
                                <label for="filterEvent">
                                    <i class="fas fa-clipboard-list"></i> Event Type
                                </label>
                                <select id="filterEvent" class="form-control">
                                    <option value="">All Events</option>
                                    <option value="academic">Academic</option>
                                    <option value="physical">Physical Fitness</option>
                                    <option value="leadership">Leadership</option>
                                    <option value="drill">Drill & Ceremony</option>
                                </select>
                            </div>
                            <div class="filter-group">
                                <label for="filterDateFrom">
                                    <i class="fas fa-calendar"></i> Date From
                                </label>
                                <input type="date" id="filterDateFrom" class="form-control">
                            </div>
                            <div class="filter-group">
                                <label for="filterDateTo">
                                    <i class="fas fa-calendar"></i> Date To
                                </label>
                                <input type="date" id="filterDateTo" class="form-control">
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Grades Table -->
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-table"></i> Recent Grades</h3>
                        <div class="card-actions">
                            <span class="badge badge-info"><?php echo count($grades); ?> records</span>
                            <button class="btn btn-primary" onclick="addNewGrade()">
                                <i class="fas fa-plus"></i> Add Grade
                            </button>
                        </div>
                    </div>
                    <div class="card-content">
                        <div class="table-container">
                            <table class="data-table" id="gradesTable">
                                <thead>
                                    <tr>
                                        <th><i class="fas fa-user-graduate"></i> Cadet</th>
                                        <th><i class="fas fa-users"></i> Platoon</th>
                                        <th><i class="fas fa-clipboard-list"></i> Event</th>
                                        <th><i class="fas fa-award"></i> Grade</th>
                                        <th><i class="fas fa-calendar"></i> Date</th>
                                        <th><i class="fas fa-comment"></i> Comments</th>
                                        <th><i class="fas fa-cogs"></i> Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if(empty($grades)): ?>
                                        <tr>
                                            <td colspan="7" class="no-data">
                                                <i class="fas fa-graduation-cap"></i>
                                                <p>No grades found</p>
                                                <button class="btn btn-primary" onclick="addNewGrade()">
                                                    <i class="fas fa-plus"></i> Add First Grade
                                                </button>
                                            </td>
                                        </tr>
                                    <?php else: ?>
                                        <?php foreach($grades as $grade): ?>
                                            <tr data-platoon="<?php echo htmlspecialchars($grade['platoon']); ?>" 
                                                data-event="<?php echo htmlspecialchars($grade['event_name']); ?>" 
                                                data-date="<?php echo htmlspecialchars($grade['created_at']); ?>">
                                                <td>
                                                    <div class="cadet-info">
                                                        <div class="cadet-name">
                                                            <?php echo htmlspecialchars($grade['last_name'] . ', ' . $grade['first_name']); ?>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td>
                                                    <span class="badge badge-outline">
                                                        Platoon <?php echo htmlspecialchars($grade['platoon']); ?>
                                                    </span>
                                                </td>
                                                <td>
                                                    <div class="event-info">
                                                        <div class="event-name">
                                                            <?php echo htmlspecialchars($grade['event_name']); ?>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td>
                                                    <div class="grade-display">
                                                        <span class="grade-value <?php echo (is_numeric($grade['grade']) && $grade['grade'] >= 80) ? 'grade-good' : ((is_numeric($grade['grade']) && $grade['grade'] >= 70) ? 'grade-average' : 'grade-poor'); ?>">
                                                            <?php echo htmlspecialchars($grade['grade']); ?>
                                                        </span>
                                                    </div>
                                                </td>
                                                <td>
                                                    <div class="date-info">
                                                        <div class="date-primary">
                                                            <?php echo date('M j, Y', strtotime($grade['created_at'])); ?>
                                                        </div>
                                                        <div class="date-secondary">
                                                            <?php echo date('g:i A', strtotime($grade['created_at'])); ?>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td>
                                                    <div class="comments-preview">
                                                        <?php if(!empty($grade['comments'])): ?>
                                                            <span class="comment-text" title="<?php echo htmlspecialchars($grade['comments']); ?>">
                                                                <?php echo htmlspecialchars(substr($grade['comments'], 0, 50) . (strlen($grade['comments']) > 50 ? '...' : '')); ?>
                                                            </span>
                                                        <?php else: ?>
                                                            <span class="no-comment">No comments</span>
                                                        <?php endif; ?>
                                                    </div>
                                                </td>
                                                <td>
                                                    <div class="action-buttons">
                                                        <button class="btn-icon" onclick="editGrade(<?php echo $grade['id']; ?>)" title="Edit Grade">
                                                            <i class="fas fa-edit"></i>
                                                        </button>
                                                        <button class="btn-icon" onclick="viewGradeDetails(<?php echo $grade['id']; ?>)" title="View Details">
                                                            <i class="fas fa-eye"></i>
                                                        </button>
                                                        <button class="btn-icon btn-danger" onclick="deleteGrade(<?php echo $grade['id']; ?>)" title="Delete Grade">
                                                            <i class="fas fa-trash"></i>
                                                        </button>
                                                    </div>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <!-- Quick Actions -->
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-bolt"></i> Quick Actions</h3>
                    </div>
                    <div class="card-content">
                        <div class="quick-actions">
                            <button class="action-card" onclick="addNewGrade()">
                                <i class="fas fa-plus-circle"></i>
                                <span>Add New Grade</span>
                                <small>Record a new grade for a cadet</small>
                            </button>
                            <button class="action-card" onclick="bulkGradeEntry()">
                                <i class="fas fa-list"></i>
                                <span>Bulk Entry</span>
                                <small>Add multiple grades at once</small>
                            </button>
                            <button class="action-card" onclick="gradeAnalytics()">
                                <i class="fas fa-chart-bar"></i>
                                <span>Analytics</span>
                                <small>View grade statistics and trends</small>
                            </button>
                            <button class="action-card" onclick="exportGrades()">
                                <i class="fas fa-file-export"></i>
                                <span>Export Data</span>
                                <small>Download grades as CSV/Excel</small>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <script src="../js/dashboard-unified.js"></script>

    <script>
        // Search functionality
        document.getElementById('searchGrades').addEventListener('input', function() {
            const searchTerm = this.value.toLowerCase();
            const rows = document.querySelectorAll('#gradesTable tbody tr');
            
            rows.forEach(row => {
                if (row.querySelector('.no-data')) return;
                
                const text = row.textContent.toLowerCase();
                row.style.display = text.includes(searchTerm) ? '' : 'none';
            });
        });

        // Filter functionality
        function applyFilters() {
            const platoonFilter = document.getElementById('filterPlatoon').value;
            const eventFilter = document.getElementById('filterEvent').value;
            const dateFromFilter = document.getElementById('filterDateFrom').value;
            const dateToFilter = document.getElementById('filterDateTo').value;
            
            const rows = document.querySelectorAll('#gradesTable tbody tr');
            
            rows.forEach(row => {
                if (row.querySelector('.no-data')) return;
                
                let show = true;
                
                // Platoon filter
                if (platoonFilter && row.dataset.platoon !== platoonFilter) {
                    show = false;
                }
                
                // Event filter
                if (eventFilter && !row.dataset.event.toLowerCase().includes(eventFilter)) {
                    show = false;
                }
                
                // Date filters
                if (dateFromFilter || dateToFilter) {
                    const rowDate = new Date(row.dataset.date);
                    if (dateFromFilter && rowDate < new Date(dateFromFilter)) {
                        show = false;
                    }
                    if (dateToFilter && rowDate > new Date(dateToFilter)) {
                        show = false;
                    }
                }
                
                row.style.display = show ? '' : 'none';
            });
        }

        // Add event listeners for filters
        ['filterPlatoon', 'filterEvent', 'filterDateFrom', 'filterDateTo'].forEach(id => {
            document.getElementById(id).addEventListener('change', applyFilters);
        });

        // Reset filters
        function resetFilters() {
            document.getElementById('filterPlatoon').value = '';
            document.getElementById('filterEvent').value = '';
            document.getElementById('filterDateFrom').value = '';
            document.getElementById('filterDateTo').value = '';
            document.getElementById('searchGrades').value = '';
            
            // Show all rows
            const rows = document.querySelectorAll('#gradesTable tbody tr');
            rows.forEach(row => {
                row.style.display = '';
            });
        }

        // Action functions
        function addNewGrade() {
            window.location.href = 'add_grade.php';
        }

        function editGrade(gradeId) {
            window.location.href = `edit_grade.php?id=${gradeId}`;
        }

        function viewGradeDetails(gradeId) {
            // This would open a modal or navigate to a details page
            alert(`View details for grade ID: ${gradeId}`);
        }

        function deleteGrade(gradeId) {
            if (confirm('Are you sure you want to delete this grade? This action cannot be undone.')) {
                // Send delete request
                window.location.href = `delete_grade.php?id=${gradeId}`;
            }
        }

        function bulkGradeEntry() {
            alert('Bulk grade entry feature coming soon!');
        }

        function gradeAnalytics() {
            alert('Grade analytics feature coming soon!');
        }

        function exportGrades() {
            // This would trigger a download
            alert('Export functionality coming soon!');
        }

        // Auto-refresh data every 30 seconds
        setInterval(function() {
            // In a real implementation, this would fetch updated data via AJAX
        }, 30000);
    </script>

    <style>
        .filter-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
        }

        .filter-group {
            display: flex;
            flex-direction: column;
            gap: 0.5rem;
        }

        .filter-group label {
            font-weight: 600;
            color: var(--text-secondary);
            font-size: 0.875rem;
            display: flex;
            align-items: center;
            gap: 0.5rem;
        }

        .table-container {
            overflow-x: auto;
        }

        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin: 0;
        }

        .data-table th,
        .data-table td {
            padding: 1rem;
            text-align: left;
            border-bottom: 1px solid var(--border-primary);
        }

        .data-table th {
            background: var(--bg-secondary);
            font-weight: 600;
            color: var(--text-secondary);
            font-size: 0.875rem;
        }

        .data-table th i {
            margin-right: 0.5rem;
            color: var(--primary);
        }

        .cadet-info {
            display: flex;
            flex-direction: column;
        }

        .cadet-name {
            font-weight: 600;
            color: var(--text-primary);
        }

        .event-info {
            display: flex;
            flex-direction: column;
        }

        .event-name {
            font-weight: 500;
            color: var(--text-primary);
        }

        .grade-display {
            display: flex;
            align-items: center;
        }

        .grade-value {
            padding: 0.25rem 0.75rem;
            border-radius: 20px;
            font-weight: 600;
            font-size: 0.875rem;
        }

        .grade-good {
            background: rgba(34, 197, 94, 0.1);
            color: #22c55e;
        }

        .grade-average {
            background: rgba(251, 191, 36, 0.1);
            color: #28a745;
        }

        .grade-poor {
            background: rgba(239, 68, 68, 0.1);
            color: #ef4444;
        }

        .date-info {
            display: flex;
            flex-direction: column;
        }

        .date-primary {
            font-weight: 500;
            color: var(--text-primary);
        }

        .date-secondary {
            font-size: 0.75rem;
            color: var(--text-secondary);
        }

        .comments-preview {
            max-width: 200px;
        }

        .comment-text {
            color: var(--text-primary);
            cursor: help;
        }

        .no-comment {
            color: var(--text-secondary);
            font-style: italic;
        }

        .action-buttons {
            display: flex;
            gap: 0.5rem;
        }

        .btn-icon {
            padding: 0.5rem;
            border: none;
            border-radius: 4px;
            background: var(--bg-secondary);
            color: var(--text-secondary);
            cursor: pointer;
            transition: all 0.2s ease;
        }

        .btn-icon:hover {
            background: var(--primary);
            color: white;
        }

        .btn-icon.btn-danger:hover {
            background: #ef4444;
            color: white;
        }

        .no-data {
            text-align: center;
            padding: 3rem;
            color: var(--text-secondary);
        }

        .no-data i {
            font-size: 3rem;
            margin-bottom: 1rem;
            color: var(--text-secondary);
        }

        .no-data p {
            margin: 1rem 0;
            font-size: 1.125rem;
        }

        .quick-actions {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
        }

        .action-card {
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 0.5rem;
            padding: 1.5rem;
            border: 1px solid var(--border-primary);
            border-radius: 8px;
            background: var(--bg-primary);
            color: var(--text-primary);
            text-decoration: none;
            transition: all 0.2s ease;
            cursor: pointer;
        }

        .action-card:hover {
            border-color: var(--primary);
            background: var(--bg-secondary);
            transform: translateY(-2px);
        }

        .action-card i {
            font-size: 2rem;
            color: var(--primary);
        }

        .action-card span {
            font-weight: 600;
            font-size: 1rem;
        }

        .action-card small {
            color: var(--text-secondary);
            font-size: 0.75rem;
            text-align: center;
        }

        @media (max-width: 768px) {
            .filter-grid {
                grid-template-columns: 1fr;
            }
            
            .data-table {
                font-size: 0.875rem;
            }
            
            .data-table th,
            .data-table td {
                padding: 0.75rem 0.5rem;
            }
            
            .action-buttons {
                flex-direction: column;
            }
            
            .quick-actions {
                grid-template-columns: 1fr;
            }
        }
    </style>
</body>
</html>
