<?php
require_once 'includes/session.php';
require_once 'includes/db.php';
require_once 'includes/SecurityLogger.php';

// Access control: Allow cadets, officers, instructors, and admins
check_login();
if (!in_array($_SESSION['role'], ['cadet', 'officer', 'instructor', 'admin', '1cl', '2cl', 'commandant'])) {
    SecurityLogger::logSecurityEvent('UNAUTHORIZED_ACCESS', 'User attempted to access rifle borrowing without proper role', $_SESSION['user_id'] ?? null, 'HIGH');
    redirect_to_dashboard();
}

// Get QR code ID from URL parameter
$qr_code_id = $_GET['qr_id'] ?? null;
if (!$qr_code_id) {
    header('Location: scanner.php');
    exit();
}

// Verify the QR code exists and is active
$sql = "SELECT * FROM dummy_qr_codes WHERE qr_code_id = ? AND is_active = 1";
$stmt = $link->prepare($sql);
$stmt->bind_param("s", $qr_code_id);
$stmt->execute();
$qr_result = $stmt->get_result();

if ($qr_result->num_rows === 0) {
    header('Location: scanner.php?error=invalid_qr');
    exit();
}

$qr_data = $qr_result->fetch_assoc();
$stmt->close();

// Get available rifles (not borrowed and in good condition)
$sql = "SELECT r.id, r.rifle_number, r.model, r.notes AS condition_notes 
        FROM rifles r 
        LEFT JOIN rifle_borrowings rb ON JSON_CONTAINS(rb.rifle_ids, CAST(r.id AS JSON)) AND rb.status = 'active'
        WHERE r.status = 'available' AND rb.id IS NULL
        ORDER BY r.rifle_number";
$rifles_result = $link->query($sql);

$available_rifles = [];
while ($row = $rifles_result->fetch_assoc()) {
    $available_rifles[] = $row;
}

$link->close();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rifle Borrowing - ROTC Management System</title>
    <link rel="stylesheet" href="css/tactical-theme.css">
    <link rel="stylesheet" href="css/dashboard-unified.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>

<body data-role="<?php echo $_SESSION['role']; ?>">
    <div class="dashboard-container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <div class="sidebar-header">
                <div class="logo">
                    <div class="logo-icon"><i class="fas fa-gun"></i></div>
                    <span>Rifle Borrowing</span>
                </div>
            </div>
            
            <nav class="sidebar-nav">
                <div class="nav-menu">
                    <!-- Navigation will be generated by JavaScript -->
                </div>
            </nav>
        </aside>

        <!-- Main Content -->
        <main class="main-content">
            <!-- Header -->
            <header class="header">
                <div class="header-left">
                    <button class="sidebar-toggle">
                        <i class="fas fa-bars"></i>
                    </button>
                    <h1 class="page-title">Rifle Borrowing</h1>
                </div>
                
                <div class="header-right">
                    <div class="header-actions">
                        <a href="scanner.php" class="action-btn" title="Back to Scanner">
                            <i class="fas fa-arrow-left"></i>
                        </a>
                        <div class="user-menu">
                            <div class="user-avatar">
                                <i class="fas fa-user"></i>
                                <span class="user-name"><?php echo htmlspecialchars($_SESSION['full_name']); ?></span>
                                <i class="fas fa-chevron-down"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <!-- Content Area -->
            <div class="content-area">
                <!-- QR Code Info -->
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-qrcode"></i> QR Code: <?php echo htmlspecialchars($qr_data['description']); ?></h3>
                        <div class="qr-status">
                            <span class="badge badge-success">Active</span>
                        </div>
                    </div>
                </div>

                <!-- Borrowing Form -->
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-user-plus"></i> Borrower Information</h3>
                    </div>
                    <div class="card-content">
                        <form id="borrowing-form" class="form-grid">
                            <input type="hidden" id="qr_code_id" value="<?php echo htmlspecialchars($qr_code_id); ?>">
                            
                            <div class="form-group">
                                <label for="borrower_name">Borrower Name *</label>
                                <input type="text" id="borrower_name" name="borrower_name" required 
                                       placeholder="Enter full name of the borrower">
                            </div>
                            
                            <div class="form-group">
                                <label for="notes">Notes (Optional)</label>
                                <textarea id="notes" name="notes" rows="3" 
                                         placeholder="Any additional notes or comments"></textarea>
                            </div>
                        </form>
                    </div>
                </div>

                <!-- Rifle Selection -->
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-list-check"></i> Select Rifles to Borrow</h3>
                        <div class="selection-summary">
                            <span id="selected-count">0</span> rifles selected
                        </div>
                    </div>
                    <div class="card-content">
                        <?php if (empty($available_rifles)): ?>
                            <div class="empty-state">
                                <i class="fas fa-exclamation-triangle"></i>
                                <h4>No Rifles Available</h4>
                                <p>All rifles are currently borrowed or unavailable.</p>
                            </div>
                        <?php else: ?>
                            <div class="rifles-grid">
                                <?php foreach ($available_rifles as $rifle): ?>
                                <div class="rifle-card" data-rifle-id="<?php echo $rifle['id']; ?>">
                                    <div class="rifle-checkbox">
                                        <input type="checkbox" id="rifle_<?php echo $rifle['id']; ?>" 
                                               value="<?php echo $rifle['id']; ?>" class="rifle-select">
                                        <label for="rifle_<?php echo $rifle['id']; ?>"></label>
                                    </div>
                                    <div class="rifle-info">
                                        <h4>Rifle #<?php echo htmlspecialchars($rifle['rifle_number']); ?></h4>
                                        <p class="rifle-model"><?php echo htmlspecialchars($rifle['model']); ?></p>
                                        <?php if ($rifle['condition_notes']): ?>
                                            <p class="rifle-condition">
                                                <i class="fas fa-info-circle"></i>
                                                <?php echo htmlspecialchars($rifle['condition_notes']); ?>
                                            </p>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>

                <!-- Action Buttons -->
                <div class="content-card">
                    <div class="card-content">
                        <div class="form-actions">
                            <button type="button" class="btn btn-secondary" onclick="window.location.href='scanner.php'">
                                <i class="fas fa-times"></i> Cancel
                            </button>
                            <button type="button" class="btn btn-primary" id="submit-borrowing" 
                                    <?php echo empty($available_rifles) ? 'disabled' : ''; ?>>
                                <i class="fas fa-check"></i> Submit Borrowing
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <script src="js/dashboard-unified.js"></script>
    <script>
        let selectedRifles = [];

        document.addEventListener('DOMContentLoaded', function() {
            // Initialize rifle selection
            const rifleCheckboxes = document.querySelectorAll('.rifle-select');
            const selectedCountElement = document.getElementById('selected-count');
            const submitButton = document.getElementById('submit-borrowing');

            rifleCheckboxes.forEach(checkbox => {
                checkbox.addEventListener('change', function() {
                    const rifleId = parseInt(this.value);
                    const rifleCard = this.closest('.rifle-card');

                    if (this.checked) {
                        selectedRifles.push(rifleId);
                        rifleCard.classList.add('selected');
                    } else {
                        selectedRifles = selectedRifles.filter(id => id !== rifleId);
                        rifleCard.classList.remove('selected');
                    }

                    selectedCountElement.textContent = selectedRifles.length;
                    submitButton.disabled = selectedRifles.length === 0;
                });
            });

            // Handle form submission
            submitButton.addEventListener('click', function() {
                const borrowerName = document.getElementById('borrower_name').value.trim();
                const notes = document.getElementById('notes').value.trim();
                const qrCodeId = document.getElementById('qr_code_id').value;

                if (!borrowerName) {
                    alert('Please enter the borrower name.');
                    return;
                }

                if (selectedRifles.length === 0) {
                    alert('Please select at least one rifle to borrow.');
                    return;
                }

                // Disable button to prevent double submission
                this.disabled = true;
                this.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Processing...';

                // Submit the borrowing request
                fetch('process_borrowing.php', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({
                        qr_code_id: qrCodeId,
                        borrower_name: borrowerName,
                        rifle_ids: selectedRifles,
                        notes: notes
                    })
                })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        alert('Rifles borrowed successfully!');
                        window.location.href = 'rifle_management.php?view=borrowings';
                    } else {
                        alert('Error: ' + data.message);
                        this.disabled = false;
                        this.innerHTML = '<i class="fas fa-check"></i> Submit Borrowing';
                    }
                })
                .catch(error => {
                    console.error('Error:', error);
                    alert('An error occurred while processing the borrowing.');
                    this.disabled = false;
                    this.innerHTML = '<i class="fas fa-check"></i> Submit Borrowing';
                });
            });
        });
    </script>

    <style>
        .form-grid {
            display: grid;
            gap: 1.5rem;
        }

        .form-group {
            display: flex;
            flex-direction: column;
            gap: 0.5rem;
        }

        .form-group label {
            font-weight: 500;
            color: var(--text-primary);
        }

        .form-group input,
        .form-group textarea {
            padding: 0.75rem;
            border: 1px solid var(--border-primary);
            border-radius: 6px;
            background: var(--bg-primary);
            color: var(--text-primary);
            font-size: 0.875rem;
        }

        .form-group input:focus,
        .form-group textarea:focus {
            outline: none;
            border-color: var(--primary);
            box-shadow: 0 0 0 3px rgba(var(--primary-rgb), 0.1);
        }

        .rifles-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
            gap: 1rem;
        }

        .rifle-card {
            border: 2px solid var(--border-primary);
            border-radius: 8px;
            padding: 1rem;
            background: var(--bg-secondary);
            transition: all 0.2s ease;
            cursor: pointer;
            display: flex;
            align-items: flex-start;
            gap: 1rem;
        }

        .rifle-card:hover {
            border-color: var(--primary);
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
        }

        .rifle-card.selected {
            border-color: var(--primary);
            background: rgba(var(--primary-rgb), 0.05);
        }

        .rifle-checkbox {
            position: relative;
        }

        .rifle-checkbox input[type="checkbox"] {
            width: 20px;
            height: 20px;
            margin: 0;
        }

        .rifle-info h4 {
            margin: 0 0 0.5rem 0;
            color: var(--text-primary);
            font-size: 1.1rem;
        }

        .rifle-model {
            margin: 0 0 0.5rem 0;
            color: var(--text-secondary);
            font-size: 0.875rem;
        }

        .rifle-condition {
            margin: 0;
            color: var(--warning);
            font-size: 0.8rem;
            display: flex;
            align-items: center;
            gap: 0.25rem;
        }

        .selection-summary {
            background: var(--bg-tertiary);
            padding: 0.5rem 1rem;
            border-radius: 20px;
            font-size: 0.875rem;
            font-weight: 500;
        }

        .form-actions {
            display: flex;
            gap: 1rem;
            justify-content: flex-end;
        }

        .empty-state {
            text-align: center;
            padding: 3rem 1rem;
            color: var(--text-secondary);
        }

        .empty-state i {
            font-size: 3rem;
            margin-bottom: 1rem;
            color: var(--warning);
        }

        .empty-state h4 {
            margin: 0 0 0.5rem 0;
            color: var(--text-primary);
        }

        .empty-state p {
            margin: 0;
        }

        @media (max-width: 768px) {
            .rifles-grid {
                grid-template-columns: 1fr;
            }

            .form-actions {
                flex-direction: column;
            }
        }
    </style>
</body>
</html>