<?php
require_once 'includes/session.php';
require_once 'includes/db.php';
require_once 'includes/SecurityLogger.php';

// Admin-only access
check_login();
if ($_SESSION['role'] !== 'admin') {
    SecurityLogger::logSecurityEvent('UNAUTHORIZED_ACCESS', 'Non-admin user attempted to access profile management', $_SESSION['user_id'] ?? null, 'HIGH');
    redirect_to_dashboard();
}

// Log successful admin access to profile management
SecurityLogger::logSecurityEvent('ADMIN_ACCESS', 'Admin accessed profile management page', $_SESSION['user_id'], 'LOW');

// Get profile statistics
$total_profiles_stmt = $pdo->query("SELECT COUNT(*) as total FROM cadet_profiles");
$total_profiles = $total_profiles_stmt->fetch()['total'];

$active_profiles_stmt = $pdo->query("SELECT COUNT(*) as total FROM cadet_profiles cp JOIN users u ON cp.user_id = u.id WHERE u.status = 'active'");
$active_profiles = $active_profiles_stmt->fetch()['total'];

$recent_profiles_stmt = $pdo->query("SELECT COUNT(*) as total FROM cadet_profiles WHERE DATE(created_at) >= DATE_SUB(CURDATE(), INTERVAL 7 DAY)");
$recent_profiles = $recent_profiles_stmt->fetch()['total'];
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadet Profile Management - ROTC Management System</title>
    <link rel="stylesheet" href="css/tactical-theme.css">
    <link rel="stylesheet" href="css/dashboard-unified.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <script src="js/dashboard-unified.js"></script>
</head>
<body data-role="admin">
    <div class="dashboard-container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <div class="sidebar-header">
                <div class="logo">
                    <div class="logo-icon"><i class="fas fa-shield-alt"></i></div>
                    <span>Admin Command Center</span>
                </div>
            </div>
            
            <nav class="sidebar-nav">
                <div class="nav-menu">
                    <!-- Navigation will be generated by JavaScript -->
                </div>
            </nav>
        </aside>

        <!-- Main Content -->
        <main class="main-content">
            <!-- Header -->
            <header class="header">
                <div class="header-left">
                    <button class="sidebar-toggle">
                        <i class="fas fa-bars"></i>
                    </button>
                    <h1 class="page-title">Cadet Profile Management</h1>
                </div>
                
                <div class="header-center">
                    <div class="search-container">
                        <i class="fas fa-search search-icon"></i>
                        <input type="text" placeholder="Search profiles..." class="search-input" id="profileSearch">
                    </div>
                </div>
                
                <div class="header-right">
                    <div class="header-actions">
                        <button class="action-btn" title="Notifications">
                            <i class="fas fa-bell"></i>
                            <span class="badge">3</span>
                        </button>
                        <div class="user-menu">
                            <div class="user-avatar">
                                <i class="fas fa-user-shield"></i>
                                <span class="user-name"><?php echo htmlspecialchars($_SESSION['full_name']); ?></span>
                                <i class="fas fa-chevron-down"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <!-- Content -->
            <div class="content">
                <!-- Statistics Cards -->
                <div class="stats-grid">
                    <div class="stat-card">
                        <div class="stat-header">
                            <div class="stat-title">Total Profiles</div>
                            <div class="stat-icon" style="background: linear-gradient(135deg, #28a745 0%, #20c997 100%);">
                                <i class="fas fa-id-card"></i>
                            </div>
                        </div>
                        <div class="stat-value"><?php echo $total_profiles; ?></div>
                        <div class="stat-change positive">
                            <i class="fas fa-users"></i>
                            <span>All cadet profiles</span>
                        </div>
                    </div>

                    <div class="stat-card">
                        <div class="stat-header">
                            <div class="stat-title">Active Profiles</div>
                            <div class="stat-icon" style="background: linear-gradient(135deg, #007bff 0%, #0056b3 100%);">
                                <i class="fas fa-user-check"></i>
                            </div>
                        </div>
                        <div class="stat-value"><?php echo $active_profiles; ?></div>
                        <div class="stat-change positive">
                            <i class="fas fa-check"></i>
                            <span>Currently active</span>
                        </div>
                    </div>

                    <div class="stat-card">
                        <div class="stat-header">
                            <div class="stat-title">New This Week</div>
                            <div class="stat-icon" style="background: linear-gradient(135deg, #6f42c1 0%, #5a2d91 100%);">
                                <i class="fas fa-user-plus"></i>
                            </div>
                        </div>
                        <div class="stat-value"><?php echo $recent_profiles; ?></div>
                        <div class="stat-change positive">
                            <i class="fas fa-calendar-week"></i>
                            <span>Last 7 days</span>
                        </div>
                    </div>
                </div>

                <!-- Profile Management Table -->
                <div class="content-card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="fas fa-id-card-alt"></i>
                            Cadet Profile Management
                        </h3>
                        <div class="card-actions">
                            <button class="btn btn-primary" onclick="window.location.href='registration.php'">
                                <i class="fas fa-user-plus"></i>
                                Add New Cadet
                            </button>
                        </div>
                    </div>
                    <div class="card-content">
                        <div class="table-container">
                            <table class="data-table" id="profilesTable">
                                <thead>
                                    <tr>
                                        <th>Profile ID</th>
                                        <th>Full Name</th>
                                        <th>Email</th>
                                        <th>Contact Number</th>
                                        <th>Platoon</th>
                                        <th>Status</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    $sql_profiles = "SELECT cp.id, cp.first_name, cp.last_name, u.email, cp.contact_number, cp.platoon, u.status
                                                 FROM cadet_profiles cp
                                                 JOIN users u ON cp.user_id = u.id
                                                 ORDER BY cp.id ASC";
                                    $result_profiles = $pdo->query($sql_profiles);

                                    if ($result_profiles->rowCount() > 0) {
                                        while($row = $result_profiles->fetch()) {
                                            $full_name = $row['first_name'] . ' ' . $row['last_name'];
                                            echo "<tr>";
                                            echo "<td>" . htmlspecialchars($row['id']) . "</td>";
                                            echo "<td>" . htmlspecialchars($full_name) . "</td>";
                                            echo "<td>" . htmlspecialchars($row['email']) . "</td>";
                                            echo "<td>" . htmlspecialchars($row['contact_number']) . "</td>";
                                            echo "<td><span class='platoon-badge'>" . htmlspecialchars($row['platoon']) . "</span></td>";
                                            echo "<td><span class='status-badge status-" . strtolower($row['status']) . "'>" . htmlspecialchars(ucfirst($row['status'])) . "</span></td>";
                                            echo "<td class='action-buttons'>";
                                            echo "<a href='view_profile.php?id=" . $row['id'] . "' class='btn btn-sm btn-primary' title='View Profile'><i class='fas fa-eye'></i></a>";
                                            echo "<a href='edit_profile.php?id=" . $row['id'] . "' class='btn btn-sm btn-success' title='Edit Profile'><i class='fas fa-edit'></i></a>";
                                            echo "</td>";
                                            echo "</tr>";
                                        }
                                    } else {
                                        echo "<tr><td colspan='7' class='text-center'>No cadet profiles found.</td></tr>";
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <style>
    .platoon-badge {
        padding: 4px 8px;
        border-radius: 12px;
        font-size: 0.75rem;
        font-weight: 600;
        background: rgba(40, 167, 69, 0.1);
        color: #28a745;
        text-transform: uppercase;
    }
    
    .status-badge {
        padding: 4px 8px;
        border-radius: 12px;
        font-size: 0.75rem;
        font-weight: 600;
        text-transform: uppercase;
    }
    .status-active { background: rgba(40, 167, 69, 0.1); color: #28a745; }
    .status-inactive { background: rgba(220, 53, 69, 0.1); color: #dc3545; }
    .status-pending { background: rgba(40, 167, 69, 0.1); color: #28a745; }
    
    .action-buttons {
        display: flex;
        gap: 8px;
    }
    
    .action-buttons .btn {
        padding: 6px 10px;
    }
    </style>

    <script>
    // Search functionality
    document.getElementById('profileSearch').addEventListener('input', function() {
        const searchTerm = this.value.toLowerCase();
        const tableRows = document.querySelectorAll('#profilesTable tbody tr');
        
        tableRows.forEach(row => {
            const text = row.textContent.toLowerCase();
            row.style.display = text.includes(searchTerm) ? '' : 'none';
        });
    });
    </script>
</body>
</html>
