<?php
require_once 'includes/session.php';
require_once 'includes/db.php';
require_once 'includes/SecurityLogger.php';

// Access control: Allow cadets, officers, instructors, and admins
check_login();
if (!in_array($_SESSION['role'], ['cadet', 'officer', 'instructor', 'admin', '1cl', '2cl', 'commandant'])) {
    SecurityLogger::logSecurityEvent('UNAUTHORIZED_ACCESS', 'User attempted to access QR scanner without proper role', $_SESSION['user_id'] ?? null, 'HIGH');
    redirect_to_dashboard();
}

// Log access to QR scanner
SecurityLogger::logSecurityEvent('DATA_ACCESS', 'User accessed QR scanner', $_SESSION['user_id'], 'LOW');

// Fetch recent attendance logs for the current user if they're a cadet
$recent_scans = [];
if ($_SESSION['role'] === 'cadet') {
    $sql = "SELECT al.event_name, al.event_date, al.time_in, al.status 
            FROM attendance_logs al 
            JOIN cadet_profiles cp ON al.cadet_profile_id = cp.id 
            WHERE cp.user_id = ? 
            ORDER BY al.event_date DESC, al.time_in DESC 
            LIMIT 10";
    $stmt = $link->prepare($sql);
    $stmt->bind_param("i", $_SESSION['user_id']);
    $stmt->execute();
    $result = $stmt->get_result();
    while ($row = $result->fetch_assoc()) {
        $recent_scans[] = $row;
    }
    $stmt->close();
}

$link->close();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QR Scanner - ROTC Management System</title>
    <link rel="stylesheet" href="css/tactical-theme.css">
    <link rel="stylesheet" href="css/dashboard-unified.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <script src="https://unpkg.com/html5-qrcode" type="text/javascript"></script>
</head>

<body data-role="<?php echo $_SESSION['role']; ?>">
    <div class="dashboard-container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <div class="sidebar-header">
                <div class="logo">
                    <div class="logo-icon"><i class="fas fa-qrcode"></i></div>
                    <span>QR Scanner</span>
                </div>
            </div>
            
            <nav class="sidebar-nav">
                <div class="nav-menu">
                    <!-- Navigation will be generated by JavaScript -->
                </div>
            </nav>
        </aside>

        <!-- Main Content -->
        <main class="main-content">
            <!-- Header -->
            <header class="header">
                <div class="header-left">
                    <button class="sidebar-toggle">
                        <i class="fas fa-bars"></i>
                    </button>
                    <h1 class="page-title">QR Code Scanner</h1>
                </div>
                
                <div class="header-right">
                    <div class="header-actions">
                        <button class="action-btn" onclick="toggleCamera()" title="Toggle Camera">
                            <i class="fas fa-camera" id="camera-icon"></i>
                        </button>
                        <div class="user-menu">
                            <div class="user-avatar">
                                <i class="fas fa-user"></i>
                                <span class="user-name"><?php echo htmlspecialchars($_SESSION['full_name']); ?></span>
                                <i class="fas fa-chevron-down"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <!-- Content Area -->
            <div class="content-area">
                <!-- Scanner Section -->
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-qrcode"></i> QR Code Scanner</h3>
                        <div class="scanner-status">
                            <span class="status-indicator" id="scanner-status">Ready</span>
                        </div>
                    </div>
                    <div class="card-content">
                        <div class="scanner-container">
                            <div id="qr-reader" class="qr-reader"></div>
                            <div id="qr-reader-results" class="scan-results"></div>
                        </div>
                        
                        <div class="scanner-controls">
                            <button class="btn btn-primary" onclick="startScanner()" id="start-btn">
                                <i class="fas fa-play"></i> Start Scanner
                            </button>
                            <button class="btn btn-secondary" onclick="stopScanner()" id="stop-btn" style="display: none;">
                                <i class="fas fa-stop"></i> Stop Scanner
                            </button>
                            <button class="btn btn-outline" onclick="clearResults()">
                                <i class="fas fa-trash"></i> Clear Results
                            </button>
                        </div>
                    </div>
                </div>

                <?php if ($_SESSION['role'] === 'cadet' && !empty($recent_scans)): ?>
                <!-- Recent Scans Section -->
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-history"></i> Recent Attendance</h3>
                    </div>
                    <div class="card-content">
                        <div class="table-responsive">
                            <table class="data-table">
                                <thead>
                                    <tr>
                                        <th>Event</th>
                                        <th>Date</th>
                                        <th>Time</th>
                                        <th>Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($recent_scans as $scan): ?>
                                    <tr>
                                        <td><?php echo htmlspecialchars($scan['event_name']); ?></td>
                                        <td><?php echo date('M d, Y', strtotime($scan['event_date'])); ?></td>
                                        <td><?php echo date('h:i A', strtotime($scan['time_in'])); ?></td>
                                        <td>
                                            <span class="badge badge-success">
                                                <?php echo htmlspecialchars(ucfirst($scan['status'])); ?>
                                            </span>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <?php endif; ?>

                <!-- Instructions Section -->
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-info-circle"></i> How to Use</h3>
                    </div>
                    <div class="card-content">
                        <div class="instructions-grid">
                            <div class="instruction-item">
                                <div class="instruction-icon">
                                    <i class="fas fa-camera"></i>
                                </div>
                                <div class="instruction-text">
                                    <h4>1. Start Scanner</h4>
                                    <p>Click the "Start Scanner" button to activate your camera</p>
                                </div>
                            </div>
                            <div class="instruction-item">
                                <div class="instruction-icon">
                                    <i class="fas fa-qrcode"></i>
                                </div>
                                <div class="instruction-text">
                                    <h4>2. Scan QR Code</h4>
                                    <p>Point your camera at the QR code until it's detected</p>
                                </div>
                            </div>
                            <div class="instruction-item">
                                <div class="instruction-icon">
                                    <i class="fas fa-check"></i>
                                </div>
                                <div class="instruction-text">
                                    <h4>3. View Results</h4>
                                    <p>Scan results will appear below the scanner</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <script src="js/dashboard-unified.js"></script>

    <script>
        let html5QrcodeScanner = null;
        let isScanning = false;

        function startScanner() {
            if (isScanning) return;

            const config = {
                fps: 10,
                qrbox: { width: 250, height: 250 },
                aspectRatio: 1.0
            };

            html5QrcodeScanner = new Html5QrcodeScanner(
                "qr-reader", config, /* verbose= */ false
            );

            html5QrcodeScanner.render(onScanSuccess, onScanFailure);
            
            isScanning = true;
            document.getElementById('start-btn').style.display = 'none';
            document.getElementById('stop-btn').style.display = 'inline-block';
            document.getElementById('scanner-status').textContent = 'Scanning...';
            document.getElementById('scanner-status').className = 'status-indicator scanning';
        }

        function stopScanner() {
            if (!isScanning || !html5QrcodeScanner) return;

            html5QrcodeScanner.clear().then(() => {
                isScanning = false;
                document.getElementById('start-btn').style.display = 'inline-block';
                document.getElementById('stop-btn').style.display = 'none';
                document.getElementById('scanner-status').textContent = 'Stopped';
                document.getElementById('scanner-status').className = 'status-indicator stopped';
            }).catch(err => {
                console.error('Error stopping scanner:', err);
            });
        }

        function toggleCamera() {
            if (isScanning) {
                stopScanner();
            } else {
                startScanner();
            }
        }

        function onScanSuccess(decodedText, decodedResult) {
            const resultsDiv = document.getElementById('qr-reader-results');
            const timestamp = new Date().toLocaleString();
            
            const resultHtml = `
                <div class="scan-result-item">
                    <div class="result-header">
                        <i class="fas fa-check-circle"></i>
                        <span class="result-time">${timestamp}</span>
                    </div>
                    <div class="result-content">
                        <strong>Scanned Data:</strong><br>
                        <code>${decodedText}</code>
                    </div>
                </div>
            `;
            
            resultsDiv.innerHTML = resultHtml + resultsDiv.innerHTML;
            
            // Update status
            document.getElementById('scanner-status').textContent = 'Scan Successful';
            document.getElementById('scanner-status').className = 'status-indicator success';
            
            // Reset status after 3 seconds
            setTimeout(() => {
                if (isScanning) {
                    document.getElementById('scanner-status').textContent = 'Scanning...';
                    document.getElementById('scanner-status').className = 'status-indicator scanning';
                }
            }, 3000);
        }

        function onScanFailure(error) {
            // Handle scan failure silently
        }

        function clearResults() {
            document.getElementById('qr-reader-results').innerHTML = '';
        }

        // Auto-start scanner when page loads
        document.addEventListener('DOMContentLoaded', function() {
            // Don't auto-start, let user control
        });
    </script>

    <style>
        .scanner-container {
            text-align: center;
            margin-bottom: 2rem;
        }

        .qr-reader {
            max-width: 500px;
            margin: 0 auto;
            border: 2px solid var(--border-primary);
            border-radius: 8px;
            overflow: hidden;
        }

        .scanner-controls {
            display: flex;
            gap: 1rem;
            justify-content: center;
            flex-wrap: wrap;
        }

        .scanner-status {
            display: flex;
            align-items: center;
            gap: 0.5rem;
        }

        .status-indicator {
            padding: 0.25rem 0.75rem;
            border-radius: 20px;
            font-size: 0.875rem;
            font-weight: 500;
            background: var(--bg-tertiary);
            color: var(--text-secondary);
        }

        .status-indicator.scanning {
            background: var(--primary);
            color: white;
        }

        .status-indicator.success {
            background: var(--success);
            color: white;
        }

        .status-indicator.stopped {
            background: var(--bg-tertiary);
            color: var(--text-muted);
        }

        .scan-results {
            max-height: 300px;
            overflow-y: auto;
            margin-top: 1rem;
        }

        .scan-result-item {
            background: var(--bg-secondary);
            border: 1px solid var(--border-primary);
            border-radius: 8px;
            padding: 1rem;
            margin-bottom: 1rem;
        }

        .result-header {
            display: flex;
            align-items: center;
            gap: 0.5rem;
            margin-bottom: 0.5rem;
            color: var(--success);
            font-weight: 500;
        }

        .result-time {
            margin-left: auto;
            font-size: 0.875rem;
            color: var(--text-secondary);
        }

        .result-content {
            color: var(--text-primary);
        }

        .result-content code {
            background: var(--bg-tertiary);
            padding: 0.25rem 0.5rem;
            border-radius: 4px;
            font-family: monospace;
            word-break: break-all;
        }

        .instructions-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 1.5rem;
        }

        .instruction-item {
            display: flex;
            align-items: flex-start;
            gap: 1rem;
        }

        .instruction-icon {
            width: 50px;
            height: 50px;
            background: var(--primary);
            color: white;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 1.25rem;
            flex-shrink: 0;
        }

        .instruction-text h4 {
            margin: 0 0 0.5rem 0;
            color: var(--text-primary);
        }

        .instruction-text p {
            margin: 0;
            color: var(--text-secondary);
            font-size: 0.875rem;
        }

        @media (max-width: 768px) {
            .scanner-controls {
                flex-direction: column;
                align-items: center;
            }

            .instructions-grid {
                grid-template-columns: 1fr;
            }
        }
    </style>
</body>
</html>