<?php
require_once 'includes/session.php';
require_once 'includes/db.php';

// Cadet-only access
check_login();
if (!in_array($_SESSION['role'], ['cadet', 'basic_cadet'])) {
    redirect_to_dashboard();
}

// Fetch cadet's schedule data
$user_id = $_SESSION['user_id'];

// Get cadet profile
$sql = "SELECT platoon FROM cadet_profiles WHERE user_id = ?";
$stmt = $link->prepare($sql);
$stmt->bind_param("i", $user_id);
$stmt->execute();
$result = $stmt->get_result();
$cadet_profile = $result->fetch_assoc();
$stmt->close();

// Fetch training schedules
$sql = "SELECT * FROM training_schedules WHERE platoon = ? OR platoon = 'All' ORDER BY training_date ASC, start_time ASC";
$stmt = $link->prepare($sql);
$platoon = $cadet_profile['platoon'] ?? 'Alpha';
$stmt->bind_param("s", $platoon);
$stmt->execute();
$result = $stmt->get_result();
$schedules = [];
while ($row = $result->fetch_assoc()) {
    $schedules[] = $row;
}
$stmt->close();

// Fetch recent attendance for this cadet
$sql = "SELECT al.event_name, al.event_date, al.time_in, al.status 
        FROM attendance_logs al 
        JOIN cadet_profiles cp ON al.cadet_profile_id = cp.id 
        WHERE cp.user_id = ? 
        ORDER BY al.event_date DESC, al.time_in DESC 
        LIMIT 5";
$stmt = $link->prepare($sql);
$stmt->bind_param("i", $user_id);
$stmt->execute();
$result = $stmt->get_result();
$recent_attendance = [];
while ($row = $result->fetch_assoc()) {
    $recent_attendance[] = $row;
}
$stmt->close();

$link->close();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Schedule - ROTC Management System</title>
    <link rel="stylesheet" href="css/tactical-theme.css">
    <link rel="stylesheet" href="css/dashboard-unified.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>

<body data-role="cadet">
    <div class="dashboard-container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <div class="sidebar-header">
                <div class="logo">
                    <div class="logo-icon"><i class="fas fa-calendar"></i></div>
                    <span>My Schedule</span>
                </div>
            </div>
            
            <nav class="sidebar-nav">
                <div class="nav-menu">
                    <!-- Navigation will be generated by JavaScript -->
                </div>
            </nav>
        </aside>

        <!-- Main Content -->
        <main class="main-content">
            <!-- Header -->
            <header class="header">
                <div class="header-left">
                    <button class="sidebar-toggle">
                        <i class="fas fa-bars"></i>
                    </button>
                    <h1 class="page-title">My Schedule</h1>
                </div>
                
                <div class="header-right">
                    <div class="header-actions">
                        <button class="action-btn" onclick="window.print()" title="Print Schedule">
                            <i class="fas fa-print"></i>
                        </button>
                        <button class="action-btn" onclick="exportSchedule()" title="Export Schedule">
                            <i class="fas fa-download"></i>
                        </button>
                        <div class="user-menu">
                            <div class="user-avatar">
                                <i class="fas fa-user"></i>
                                <span class="user-name"><?php echo htmlspecialchars($_SESSION['full_name']); ?></span>
                                <i class="fas fa-chevron-down"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <!-- Content Area -->
            <div class="content-area">
                <!-- Schedule Overview -->
                <div class="stats-grid">
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-calendar-week"></i>
                        </div>
                        <div class="stat-content">
                            <div class="stat-number"><?php echo count($schedules); ?></div>
                            <div class="stat-label">Scheduled Events</div>
                        </div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        <div class="stat-content">
                            <div class="stat-number"><?php echo htmlspecialchars($platoon); ?></div>
                            <div class="stat-label">Platoon</div>
                        </div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-check-circle"></i>
                        </div>
                        <div class="stat-content">
                            <div class="stat-number"><?php echo count($recent_attendance); ?></div>
                            <div class="stat-label">Recent Attendance</div>
                        </div>
                    </div>
                </div>

                <!-- Training Schedule -->
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-calendar-alt"></i> Training Schedule</h3>
                        <div class="card-actions">
                            <select class="filter-select" id="weekFilter" onchange="filterByWeek()">
                                <option value="all">All Weeks</option>
                                <option value="current">Current Week</option>
                                <option value="next">Next Week</option>
                            </select>
                        </div>
                    </div>
                    <div class="card-content">
                        <?php if (!empty($schedules)): ?>
                            <div class="schedule-timeline">
                                <?php 
                                $current_date = null;
                                foreach ($schedules as $schedule): 
                                    $schedule_date = date('Y-m-d', strtotime($schedule['training_date']));
                                    if ($current_date !== $schedule_date):
                                        if ($current_date !== null): echo '</div>'; endif;
                                        $current_date = $schedule_date;
                                ?>
                                    <div class="schedule-day" data-date="<?php echo $schedule_date; ?>">
                                        <div class="day-header">
                                            <h4><?php echo date('l, F j, Y', strtotime($schedule['training_date'])); ?></h4>
                                        </div>
                                        <div class="day-events">
                                <?php endif; ?>
                                            <div class="schedule-event">
                                                <div class="event-time">
                                                    <i class="fas fa-clock"></i>
                                                    <?php echo date('h:i A', strtotime($schedule['start_time'])); ?>
                                                    <?php if ($schedule['end_time']): ?>
                                                        - <?php echo date('h:i A', strtotime($schedule['end_time'])); ?>
                                                    <?php endif; ?>
                                                </div>
                                                <div class="event-details">
                                                    <h5><?php echo htmlspecialchars($schedule['activity_name']); ?></h5>
                                                    <p><?php echo htmlspecialchars($schedule['description'] ?? 'No description available'); ?></p>
                                                    <div class="event-meta">
                                                        <span class="event-location">
                                                            <i class="fas fa-map-marker-alt"></i>
                                                            <?php echo htmlspecialchars($schedule['location'] ?? 'TBA'); ?>
                                                        </span>
                                                        <span class="event-instructor">
                                                            <i class="fas fa-user-tie"></i>
                                                            <?php echo htmlspecialchars($schedule['instructor'] ?? 'TBA'); ?>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                <?php endforeach; ?>
                                <?php if ($current_date !== null): ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        <?php else: ?>
                            <div class="empty-state">
                                <i class="fas fa-calendar-times"></i>
                                <h4>No Scheduled Events</h4>
                                <p>There are currently no training events scheduled for your platoon.</p>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>

                <!-- Recent Attendance -->
                <?php if (!empty($recent_attendance)): ?>
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-history"></i> Recent Attendance</h3>
                        <div class="card-actions">
                            <button class="btn btn-outline" onclick="window.location.href='attendance/logs.php'">
                                View All
                            </button>
                        </div>
                    </div>
                    <div class="card-content">
                        <div class="table-responsive">
                            <table class="data-table">
                                <thead>
                                    <tr>
                                        <th>Event</th>
                                        <th>Date</th>
                                        <th>Time</th>
                                        <th>Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($recent_attendance as $attendance): ?>
                                    <tr>
                                        <td><?php echo htmlspecialchars($attendance['event_name']); ?></td>
                                        <td><?php echo date('M d, Y', strtotime($attendance['event_date'])); ?></td>
                                        <td><?php echo date('h:i A', strtotime($attendance['time_in'])); ?></td>
                                        <td>
                                            <span class="badge badge-success">
                                                <?php echo htmlspecialchars(ucfirst($attendance['status'])); ?>
                                            </span>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <?php endif; ?>
            </div>
        </main>
    </div>

    <script src="js/dashboard-unified.js"></script>

    <script>
        function filterByWeek() {
            const filter = document.getElementById('weekFilter').value;
            const scheduleDays = document.querySelectorAll('.schedule-day');
            const today = new Date();
            const currentWeekStart = new Date(today.setDate(today.getDate() - today.getDay()));
            const currentWeekEnd = new Date(currentWeekStart);
            currentWeekEnd.setDate(currentWeekEnd.getDate() + 6);
            
            const nextWeekStart = new Date(currentWeekEnd);
            nextWeekStart.setDate(nextWeekStart.getDate() + 1);
            const nextWeekEnd = new Date(nextWeekStart);
            nextWeekEnd.setDate(nextWeekEnd.getDate() + 6);

            scheduleDays.forEach(day => {
                const dayDate = new Date(day.dataset.date);
                let show = true;

                if (filter === 'current') {
                    show = dayDate >= currentWeekStart && dayDate <= currentWeekEnd;
                } else if (filter === 'next') {
                    show = dayDate >= nextWeekStart && dayDate <= nextWeekEnd;
                }

                day.style.display = show ? 'block' : 'none';
            });
        }

        function exportSchedule() {
            // Simple export functionality
            const scheduleData = [];
            document.querySelectorAll('.schedule-event').forEach(event => {
                const time = event.querySelector('.event-time').textContent.trim();
                const title = event.querySelector('h5').textContent.trim();
                const description = event.querySelector('p').textContent.trim();
                scheduleData.push(`${time} - ${title}: ${description}`);
            });

            const blob = new Blob([scheduleData.join('\n')], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'my-schedule.txt';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        }
    </script>

    <style>
        .schedule-timeline {
            display: flex;
            flex-direction: column;
            gap: 2rem;
        }

        .schedule-day {
            border-left: 4px solid var(--primary);
            padding-left: 1.5rem;
        }

        .day-header {
            margin-bottom: 1rem;
        }

        .day-header h4 {
            margin: 0;
            color: var(--text-primary);
            font-size: 1.25rem;
        }

        .day-events {
            display: flex;
            flex-direction: column;
            gap: 1rem;
        }

        .schedule-event {
            background: var(--bg-secondary);
            border: 1px solid var(--border-primary);
            border-radius: 8px;
            padding: 1.5rem;
            display: flex;
            gap: 1.5rem;
        }

        .event-time {
            flex-shrink: 0;
            width: 120px;
            color: var(--primary);
            font-weight: 600;
            display: flex;
            align-items: center;
            gap: 0.5rem;
        }

        .event-details {
            flex: 1;
        }

        .event-details h5 {
            margin: 0 0 0.5rem 0;
            color: var(--text-primary);
            font-size: 1.1rem;
        }

        .event-details p {
            margin: 0 0 1rem 0;
            color: var(--text-secondary);
            line-height: 1.5;
        }

        .event-meta {
            display: flex;
            gap: 1.5rem;
            flex-wrap: wrap;
        }

        .event-location,
        .event-instructor {
            display: flex;
            align-items: center;
            gap: 0.5rem;
            color: var(--text-muted);
            font-size: 0.875rem;
        }

        .filter-select {
            padding: 0.5rem 1rem;
            border: 1px solid var(--border-primary);
            border-radius: 6px;
            background: var(--bg-primary);
            color: var(--text-primary);
            font-size: 0.875rem;
        }

        @media (max-width: 768px) {
            .schedule-event {
                flex-direction: column;
                gap: 1rem;
            }

            .event-time {
                width: auto;
            }

            .event-meta {
                flex-direction: column;
                gap: 0.5rem;
            }
        }
    </style>
</body>
</html>
