<?php
// Simple test for rifle QR encryption without database dependencies

echo "<h2>Testing Rifle QR Encryption</h2>";

// Test data similar to what would be in a rifle QR
$test_data = array(
    'rifle_id' => '12345',
    'serial' => 'TEST001',
    'type' => 'rifle',
    'system' => 'rotc_rifle_management'
);

$json_data = json_encode($test_data);
$encryption_key = 'rifle-management-system-key-2024';

echo "<h3>Original Data:</h3>";
echo "<pre>" . htmlspecialchars($json_data) . "</pre>";

// Generate a random IV for AES encryption
$iv = openssl_random_pseudo_bytes(16);

// Encrypt using AES-256-CBC to match CryptoJS format
$encrypted = openssl_encrypt($json_data, 'AES-256-CBC', $encryption_key, OPENSSL_RAW_DATA, $iv);

// Combine IV and encrypted data, then base64 encode (CryptoJS format)
$encrypted_data = base64_encode($iv . $encrypted);

echo "<h3>Encrypted Data (Base64):</h3>";
echo "<pre>" . htmlspecialchars($encrypted_data) . "</pre>";

// Test decryption to verify it works
$decoded = base64_decode($encrypted_data);
$iv_extracted = substr($decoded, 0, 16);
$encrypted_extracted = substr($decoded, 16);

$decrypted = openssl_decrypt($encrypted_extracted, 'AES-256-CBC', $encryption_key, OPENSSL_RAW_DATA, $iv_extracted);

echo "<h3>Decrypted Data:</h3>";
echo "<pre>" . htmlspecialchars($decrypted) . "</pre>";

if ($decrypted === $json_data) {
    echo "<p style='color: green; font-size: 18px;'><strong>✓ Encryption/Decryption Test PASSED!</strong></p>";
    echo "<p style='color: green;'>The AES encryption is working correctly and should be compatible with CryptoJS decryption in the rifle scanner.</p>";
} else {
    echo "<p style='color: red; font-size: 18px;'><strong>✗ Encryption/Decryption Test FAILED!</strong></p>";
    echo "<p style='color: red;'>There is an issue with the encryption/decryption process.</p>";
}

// Test the exact format that would be generated by the QR function
echo "<h3>Testing QR Generation Format:</h3>";

// Simulate the exact QR data structure
$qr_data = array(
    'rifle_id' => '54545',
    'serial' => 'RIFLE_54545',
    'type' => 'rifle',
    'system' => 'rotc_rifle_management'
);

$qr_json = json_encode($qr_data);
$qr_iv = openssl_random_pseudo_bytes(16);
$qr_encrypted = openssl_encrypt($qr_json, 'AES-256-CBC', $encryption_key, OPENSSL_RAW_DATA, $qr_iv);
$qr_encrypted_data = base64_encode($qr_iv . $qr_encrypted);

echo "<p><strong>QR Data JSON:</strong></p>";
echo "<pre>" . htmlspecialchars($qr_json) . "</pre>";
echo "<p><strong>QR Encrypted Data:</strong></p>";
echo "<pre>" . htmlspecialchars($qr_encrypted_data) . "</pre>";

// Test decryption
$qr_decoded = base64_decode($qr_encrypted_data);
$qr_iv_extracted = substr($qr_decoded, 0, 16);
$qr_encrypted_extracted = substr($qr_decoded, 16);
$qr_decrypted = openssl_decrypt($qr_encrypted_extracted, 'AES-256-CBC', $encryption_key, OPENSSL_RAW_DATA, $qr_iv_extracted);

if ($qr_decrypted === $qr_json) {
    echo "<p style='color: green;'><strong>✓ QR Format Test PASSED!</strong></p>";
} else {
    echo "<p style='color: red;'><strong>✗ QR Format Test FAILED!</strong></p>";
}

echo "<h3>Instructions:</h3>";
echo "<p>If both tests pass, the rifle QR codes should now be scannable by the rifle scanner.</p>";
echo "<p>The encryption format matches what CryptoJS expects for decryption.</p>";
?>