<?php
require_once '../includes/session.php';
require_once '../includes/db.php';
check_login();

// Access control: Allow admins, instructors, officers, and higher ranks
if(!in_array($_SESSION['role'], ['admin', 'instructor', 'officer', '1cl', '2cl', 'commandant'])){
    die('Access Denied. You do not have permission to generate reports.');
}

// Get statistics for dashboard
$total_cadets_sql = "SELECT COUNT(*) as total FROM users WHERE role IN ('cadet', 'basic_cadet')";
$total_cadets_result = mysqli_query($link, $total_cadets_sql);
$total_cadets = mysqli_fetch_assoc($total_cadets_result)['total'] ?? 0;

$total_attendance_sql = "SELECT COUNT(*) as total FROM attendance_logs";
$total_attendance_result = mysqli_query($link, $total_attendance_sql);
$total_attendance = mysqli_fetch_assoc($total_attendance_result)['total'] ?? 0;

$total_grades_sql = "SELECT COUNT(*) as total FROM grades";
$total_grades_result = mysqli_query($link, $total_grades_sql);
$total_grades = mysqli_fetch_assoc($total_grades_result)['total'] ?? 0;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generate Reports - ROTC Management System</title>
    <link rel="stylesheet" href="../css/tactical-theme.css">
    <link rel="stylesheet" href="../css/dashboard-unified.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>

<body data-role="<?php echo $_SESSION['role']; ?>">
    <div class="dashboard-container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <div class="sidebar-header">
                <div class="logo">
                    <div class="logo-icon"><i class="fas fa-chart-bar"></i></div>
                    <span>Generate Reports</span>
                </div>
            </div>
            
            <nav class="sidebar-nav">
                <div class="nav-menu">
                    <!-- Navigation will be generated by JavaScript -->
                </div>
            </nav>
        </aside>

        <!-- Main Content -->
        <main class="main-content">
            <!-- Header -->
            <header class="header">
                <div class="header-left">
                    <button class="sidebar-toggle">
                        <i class="fas fa-bars"></i>
                    </button>
                    <h1 class="page-title">Generate Reports</h1>
                </div>
                
                <div class="header-right">
                    <div class="header-actions">
                        <button class="action-btn" onclick="window.print()" title="Print Page">
                            <i class="fas fa-print"></i>
                        </button>
                        <button class="action-btn" onclick="refreshData()" title="Refresh Data">
                            <i class="fas fa-sync-alt"></i>
                        </button>
                        <div class="user-menu">
                            <div class="user-avatar">
                                <i class="fas fa-user"></i>
                                <span class="user-name"><?php echo htmlspecialchars($_SESSION['full_name']); ?></span>
                                <i class="fas fa-chevron-down"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <!-- Content Area -->
            <div class="content-area">
                <!-- Statistics -->
                <div class="stats-grid">
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        <div class="stat-content">
                            <div class="stat-number"><?php echo $total_cadets; ?></div>
                            <div class="stat-label">Total Cadets</div>
                        </div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-clipboard-list"></i>
                        </div>
                        <div class="stat-content">
                            <div class="stat-number"><?php echo $total_attendance; ?></div>
                            <div class="stat-label">Attendance Records</div>
                        </div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-graduation-cap"></i>
                        </div>
                        <div class="stat-content">
                            <div class="stat-number"><?php echo $total_grades; ?></div>
                            <div class="stat-label">Grade Records</div>
                        </div>
                    </div>
                </div>

                <!-- Report Generation Form -->
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-file-alt"></i> Generate System Reports</h3>
                        <div class="card-actions">
                            <span class="badge badge-info">Report Generator</span>
                        </div>
                    </div>
                    <div class="card-content">
                        <form action="view_report.php" method="get" target="_blank" class="report-form">
                            <div class="form-grid">
                                <div class="form-group">
                                    <label for="report_type">
                                        <i class="fas fa-chart-bar"></i> Select Report Type
                                    </label>
                                    <select name="report_type" id="report_type" class="form-control" required>
                                        <option value="">-- Select a Report --</option>
                                        <option value="attendance">📊 Attendance Report</option>
                                        <option value="grades">🎓 Grades Report</option>
                                        <option value="cadet_summary">👥 Cadet Summary Report</option>
                                        <option value="performance">📈 Performance Analytics</option>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="date_range">
                                        <i class="fas fa-calendar-alt"></i> Date Range
                                    </label>
                                    <select name="date_range" id="date_range" class="form-control">
                                        <option value="all">All Time</option>
                                        <option value="today">Today</option>
                                        <option value="week">This Week</option>
                                        <option value="month">This Month</option>
                                        <option value="semester">This Semester</option>
                                        <option value="custom">Custom Range</option>
                                    </select>
                                </div>

                                <div class="form-group custom-date-range" style="display: none;">
                                    <label for="start_date">
                                        <i class="fas fa-calendar"></i> Start Date
                                    </label>
                                    <input type="date" name="start_date" id="start_date" class="form-control">
                                </div>

                                <div class="form-group custom-date-range" style="display: none;">
                                    <label for="end_date">
                                        <i class="fas fa-calendar"></i> End Date
                                    </label>
                                    <input type="date" name="end_date" id="end_date" class="form-control">
                                </div>

                                <div class="form-group">
                                    <label for="format">
                                        <i class="fas fa-file-export"></i> Export Format
                                    </label>
                                    <select name="format" id="format" class="form-control">
                                        <option value="html">📄 HTML (Web View)</option>
                                        <option value="pdf">📋 PDF Document</option>
                                        <option value="csv">📊 CSV Spreadsheet</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-actions">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fas fa-file-alt"></i> Generate Report
                                </button>
                                <button type="button" class="btn btn-outline" onclick="previewReport()">
                                    <i class="fas fa-eye"></i> Preview
                                </button>
                            </div>
                        </form>
                    </div>
                </div>

                <!-- Quick Report Templates -->
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-bolt"></i> Quick Report Templates</h3>
                    </div>
                    <div class="card-content">
                        <div class="quick-reports">
                            <button class="report-template" onclick="generateQuickReport('daily_attendance')">
                                <i class="fas fa-calendar-day"></i>
                                <span>Daily Attendance</span>
                                <small>Today's attendance summary</small>
                            </button>
                            <button class="report-template" onclick="generateQuickReport('weekly_summary')">
                                <i class="fas fa-calendar-week"></i>
                                <span>Weekly Summary</span>
                                <small>This week's overview</small>
                            </button>
                            <button class="report-template" onclick="generateQuickReport('grade_analysis')">
                                <i class="fas fa-chart-line"></i>
                                <span>Grade Analysis</span>
                                <small>Performance metrics</small>
                            </button>
                            <button class="report-template" onclick="generateQuickReport('cadet_roster')">
                                <i class="fas fa-users"></i>
                                <span>Cadet Roster</span>
                                <small>Complete cadet list</small>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <script src="../js/dashboard-unified.js"></script>

    <script>
        // Handle custom date range visibility
        document.getElementById('date_range').addEventListener('change', function() {
            const customRangeElements = document.querySelectorAll('.custom-date-range');
            if (this.value === 'custom') {
                customRangeElements.forEach(el => el.style.display = 'block');
            } else {
                customRangeElements.forEach(el => el.style.display = 'none');
            }
        });

        // Preview report function
        function previewReport() {
            const reportType = document.getElementById('report_type').value;
            const dateRange = document.getElementById('date_range').value;
            
            if (!reportType) {
                alert('Please select a report type first.');
                return;
            }
            
            // Open preview in new tab
            const params = new URLSearchParams({
                report_type: reportType,
                date_range: dateRange,
                preview: 'true'
            });
            
            window.open(`view_report.php?${params.toString()}`, '_blank');
        }

        // Generate quick reports
        function generateQuickReport(template) {
            let reportType, dateRange;
            
            switch(template) {
                case 'daily_attendance':
                    reportType = 'attendance';
                    dateRange = 'today';
                    break;
                case 'weekly_summary':
                    reportType = 'attendance';
                    dateRange = 'week';
                    break;
                case 'grade_analysis':
                    reportType = 'grades';
                    dateRange = 'semester';
                    break;
                case 'cadet_roster':
                    reportType = 'cadet_summary';
                    dateRange = 'all';
                    break;
            }
            
            const params = new URLSearchParams({
                report_type: reportType,
                date_range: dateRange,
                format: 'html'
            });
            
            window.open(`view_report.php?${params.toString()}`, '_blank');
        }

        // Refresh data function
        function refreshData() {
            window.location.reload();
        }

        // Form validation
        document.querySelector('.report-form').addEventListener('submit', function(e) {
            const reportType = document.getElementById('report_type').value;
            const dateRange = document.getElementById('date_range').value;
            
            if (!reportType) {
                e.preventDefault();
                alert('Please select a report type.');
                return;
            }
            
            if (dateRange === 'custom') {
                const startDate = document.getElementById('start_date').value;
                const endDate = document.getElementById('end_date').value;
                
                if (!startDate || !endDate) {
                    e.preventDefault();
                    alert('Please select both start and end dates for custom range.');
                    return;
                }
                
                if (new Date(startDate) > new Date(endDate)) {
                    e.preventDefault();
                    alert('Start date cannot be later than end date.');
                    return;
                }
            }
        });
    </script>

    <style>
        .report-form {
            margin: 0;
        }

        .form-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 1.5rem;
            margin-bottom: 2rem;
        }

        .form-group {
            display: flex;
            flex-direction: column;
            gap: 0.5rem;
        }

        .form-group label {
            font-weight: 600;
            color: var(--text-secondary);
            font-size: 0.875rem;
            display: flex;
            align-items: center;
            gap: 0.5rem;
        }

        .form-control {
            padding: 0.75rem;
            border: 1px solid var(--border-primary);
            border-radius: 6px;
            background: var(--bg-primary);
            color: var(--text-primary);
            font-size: 0.875rem;
            transition: all 0.2s ease;
        }

        .form-control:focus {
            outline: none;
            border-color: var(--primary);
            box-shadow: 0 0 0 3px rgba(var(--primary-rgb), 0.1);
        }

        .form-actions {
            display: flex;
            gap: 1rem;
            justify-content: flex-start;
            padding-top: 1rem;
            border-top: 1px solid var(--border-primary);
        }

        .quick-reports {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
        }

        .report-template {
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 0.5rem;
            padding: 1.5rem;
            border: 1px solid var(--border-primary);
            border-radius: 8px;
            background: var(--bg-primary);
            color: var(--text-primary);
            text-decoration: none;
            transition: all 0.2s ease;
            cursor: pointer;
        }

        .report-template:hover {
            border-color: var(--primary);
            background: var(--bg-secondary);
            transform: translateY(-2px);
        }

        .report-template i {
            font-size: 2rem;
            color: var(--primary);
        }

        .report-template span {
            font-weight: 600;
            font-size: 1rem;
        }

        .report-template small {
            color: var(--text-secondary);
            font-size: 0.75rem;
            text-align: center;
        }

        .custom-date-range {
            transition: all 0.3s ease;
        }

        @media (max-width: 768px) {
            .form-grid {
                grid-template-columns: 1fr;
            }
            
            .form-actions {
                flex-direction: column;
            }
            
            .quick-reports {
                grid-template-columns: 1fr;
            }
        }
    </style>
</body>
</html>
