<?php
require_once '../includes/session.php';
require_once '../includes/db.php';
require_once '../includes/SecurityLogger.php';

// Access control: Allow Admins, Instructors, Officers, and specific roles
check_login();
if (!in_array($_SESSION['role'], ['admin', 'instructor', 'officer', '1cl', '2cl', 'commandant', 'cadet', 'basic_cadet'])) {
    SecurityLogger::logSecurityEvent('UNAUTHORIZED_ACCESS', 'User attempted to access attendance logs without proper role', $_SESSION['user_id'] ?? null, 'HIGH');
    redirect_to_dashboard();
}

// Log access to attendance logs
SecurityLogger::logSecurityEvent('DATA_ACCESS', 'User accessed attendance logs', $_SESSION['user_id'], 'LOW');

// If cadet, only show their own logs
$cadet_filter = '';
if (in_array($_SESSION['role'], ['cadet', 'basic_cadet'])) {
    $cadet_filter = $_SESSION['user_id'];
}

// --- Filtering Logic ---
$filter_event = $_GET['event_name'] ?? '';
$filter_date = $_GET['event_date'] ?? '';
$filter_cadet = $_GET['cadet_name'] ?? '';

// --- Fetch Distinct Event Names for Filter Dropdown ---
$event_names = [];
$event_result = $link->query("SELECT DISTINCT event_name FROM attendance_logs ORDER BY event_name");
while ($row = $event_result->fetch_assoc()) {
    $event_names[] = $row['event_name'];
}

// --- Build SQL Query ---
$sql = "SELECT al.event_name, al.event_date, al.time_in, al.status, CONCAT(cp.first_name, ' ', cp.last_name) AS cadet_name, u.username AS logged_by_username
        FROM attendance_logs al
        JOIN cadet_profiles cp ON al.cadet_profile_id = cp.id
        JOIN users u ON al.logged_by_user_id = u.id";

$where_clauses = [];
$params = [];
$types = '';

if (!empty($filter_event)) {
    $where_clauses[] = "al.event_name = ?";
    $params[] = $filter_event;
    $types .= 's';
}
if (!empty($filter_date)) {
    $where_clauses[] = "al.event_date = ?";
    $params[] = $filter_date;
    $types .= 's';
}
if (!empty($filter_cadet)) {
    $where_clauses[] = "CONCAT(cp.first_name, ' ', cp.last_name) LIKE ?";
    $params[] = "%{$filter_cadet}%";
    $types .= 's';
}

if (!empty($where_clauses)) {
    $sql .= " WHERE " . implode(' AND ', $where_clauses);
}

// Order by date ascending to number training days chronologically
$sql .= " ORDER BY al.event_date ASC, al.time_in ASC";

$stmt = $link->prepare($sql);
if (!empty($params)) {
    $stmt->bind_param($types, ...$params);
}
$stmt->execute();
$result = $stmt->get_result();

// Group logs by date
$logs_by_date = [];
while ($row = $result->fetch_assoc()) {
    $logs_by_date[$row['event_date']][] = $row;
}

// If cadet, filter to only their records
if (in_array($_SESSION['role'], ['cadet', 'basic_cadet'])) {
    $sql .= " JOIN cadet_profiles cp2 ON al.cadet_profile_id = cp2.id WHERE cp2.user_id = ?";
    if (!empty($where_clauses)) {
        $sql .= " AND " . implode(' AND ', $where_clauses);
    }
    array_unshift($params, $_SESSION['user_id']);
    $types = 'i' . $types;
} else {
    if (!empty($where_clauses)) {
        $sql .= " WHERE " . implode(' AND ', $where_clauses);
    }
}

$stmt->close();
$link->close();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Attendance Logs - ROTC Management System</title>
    <link rel="stylesheet" href="../css/tactical-theme.css">
    <link rel="stylesheet" href="../css/dashboard-unified.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>

<body data-role="<?php echo $_SESSION['role']; ?>">
    <div class="dashboard-container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <div class="sidebar-header">
                <div class="logo">
                    <div class="logo-icon"><i class="fas fa-clipboard-list"></i></div>
                    <span>Attendance Logs</span>
                </div>
            </div>
            
            <nav class="sidebar-nav">
                <div class="nav-menu">
                    <!-- Navigation will be generated by JavaScript -->
                </div>
            </nav>
        </aside>

        <!-- Main Content -->
        <main class="main-content">
            <!-- Header -->
            <header class="header">
                <div class="header-left">
                    <button class="sidebar-toggle">
                        <i class="fas fa-bars"></i>
                    </button>
                    <h1 class="page-title">Attendance Logs</h1>
                </div>
                
                <div class="header-right">
                    <div class="header-actions">
                        <div class="search-container">
                            <input type="text" class="search-input" placeholder="Search logs..." id="searchInput">
                            <i class="fas fa-search search-icon"></i>
                        </div>
                        <button class="action-btn" onclick="window.print()" title="Print Logs">
                            <i class="fas fa-print"></i>
                        </button>
                        <button class="action-btn" onclick="exportLogs()" title="Export Logs">
                            <i class="fas fa-download"></i>
                        </button>
                        <div class="user-menu">
                            <div class="user-avatar">
                                <i class="fas fa-user"></i>
                                <span class="user-name"><?php echo htmlspecialchars($_SESSION['full_name']); ?></span>
                                <i class="fas fa-chevron-down"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <!-- Content Area -->
            <div class="content-area">
                <!-- Filter Section -->
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-filter"></i> Filter Records</h3>
                        <button class="btn btn-outline" onclick="clearFilters()">
                            <i class="fas fa-times"></i> Clear Filters
                        </button>
                    </div>
                    <div class="card-content">
                        <form action="" method="GET" class="filter-form">
                            <div class="filter-grid">
                                <div class="filter-group">
                                    <label for="eventName">Event Name</label>
                                    <select name="event_name" id="eventName" class="form-control">
                                        <option value="">All Events</option>
                                        <?php foreach ($event_names as $event): ?>
                                            <option value="<?php echo htmlspecialchars($event); ?>" <?php echo ($filter_event == $event) ? 'selected' : ''; ?>>
                                                <?php echo htmlspecialchars($event); ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                                <div class="filter-group">
                                    <label for="eventDate">Date</label>
                                    <input type="date" name="event_date" id="eventDate" class="form-control" value="<?php echo htmlspecialchars($filter_date); ?>">
                                </div>
                                <?php if (!in_array($_SESSION['role'], ['cadet', 'basic_cadet'])): ?>
                                <div class="filter-group">
                                    <label for="cadetName">Cadet Name</label>
                                    <input type="text" name="cadet_name" id="cadetName" class="form-control" placeholder="Search cadet..." value="<?php echo htmlspecialchars($filter_cadet); ?>">
                                </div>
                                <?php endif; ?>
                                <?php if (!in_array($_SESSION['role'], ['cadet', 'basic_cadet'])): ?>
                                <div class="filter-group">
                                    <label for="status">Status</label>
                                    <select name="status" id="status" class="form-control">
                                        <option value="">All Statuses</option>
                                        <option value="present" <?php echo $filter_status === 'present' ? 'selected' : ''; ?>>Present</option>
                                        <option value="late" <?php echo $filter_status === 'late' ? 'selected' : ''; ?>>Late</option>
                                        <option value="absent" <?php echo $filter_status === 'absent' ? 'selected' : ''; ?>>Absent</option>
                                    </select>
                                </div>
                                <?php endif; ?>
                                <div class="filter-group">
                                    <label>&nbsp;</label>
                                    <button type="submit" class="btn btn-primary">
                                        <i class="fas fa-search"></i> Apply Filters
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <!-- Statistics -->
                <div class="stats-grid">
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-calendar-day"></i>
                        </div>
                        <div class="stat-content">
                            <div class="stat-number"><?php echo count($logs_by_date); ?></div>
                            <div class="stat-label">Training Days</div>
                        </div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        <div class="stat-content">
                            <div class="stat-number"><?php echo array_sum(array_map('count', $logs_by_date)); ?></div>
                            <div class="stat-label">Total Records</div>
                        </div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-check-circle"></i>
                        </div>
                        <div class="stat-content">
                            <div class="stat-number">100%</div>
                            <div class="stat-label">Attendance Rate</div>
                        </div>
                    </div>
                </div>

                <!-- Attendance Logs -->
                <?php if (!empty($logs_by_date)): ?>
                    <?php $training_day_counter = 1; ?>
                    <?php foreach ($logs_by_date as $date => $logs): ?>
                        <div class="content-card training-day-card">
                            <div class="card-header">
                                <h3>
                                    <i class="fas fa-calendar-alt"></i>
                                    Training Day <?php echo $training_day_counter++; ?>: <?php echo date('l, F j, Y', strtotime($date)); ?>
                                </h3>
                                <div class="card-actions">
                                    <span class="badge badge-primary"><?php echo count($logs); ?> Records</span>
                                </div>
                            </div>
                            <div class="card-content">
                                <div class="table-responsive">
                                    <table class="data-table">
                                        <thead>
                                            <tr>
                                                <th>Event Name</th>
                                                <th>Time In</th>
                                                <?php if (!in_array($_SESSION['role'], ['cadet', 'basic_cadet'])): ?>
                                                <th>Cadet Name</th>
                                                <?php endif; ?>
                                                <th>Status</th>
                                                <?php if (!in_array($_SESSION['role'], ['cadet', 'basic_cadet'])): ?>
                                                <th>Logged By</th>
                                                <?php endif; ?>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($logs as $row): ?>
                                                <tr>
                                                    <td><?php echo htmlspecialchars($row['event_name']); ?></td>
                                                    <td><?php echo date('h:i A', strtotime($row['time_in'])); ?></td>
                                                    <?php if (!in_array($_SESSION['role'], ['cadet', 'basic_cadet'])): ?>
                                                    <td><?php echo htmlspecialchars($row['cadet_name']); ?></td>
                                                    <?php endif; ?>
                                                    <td>
                                                        <span class="badge badge-success">
                                                            <?php echo htmlspecialchars(ucfirst($row['status'])); ?>
                                                        </span>
                                                    </td>
                                                    <?php if (!in_array($_SESSION['role'], ['cadet', 'basic_cadet'])): ?>
                                                    <td><?php echo htmlspecialchars($row['logged_by_username']); ?></td>
                                                    <?php endif; ?>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                <?php else: ?>
                    <div class="empty-state">
                        <i class="fas fa-clipboard-list"></i>
                        <h4>No Attendance Records Found</h4>
                        <p>No attendance records match your current filter criteria.</p>
                        <button class="btn btn-primary" onclick="clearFilters()">
                            <i class="fas fa-refresh"></i> Clear Filters
                        </button>
                    </div>
                <?php endif; ?>
            </div>
        </main>
    </div>

    <script src="../js/dashboard-unified.js"></script>

    <script>
        function clearFilters() {
            window.location.href = 'logs.php';
        }

        function exportLogs() {
            const logs = [];
            document.querySelectorAll('.data-table tbody tr').forEach(row => {
                const cells = row.querySelectorAll('td');
                const logData = Array.from(cells).map(cell => cell.textContent.trim()).join('\t');
                logs.push(logData);
            });

            const headers = Array.from(document.querySelectorAll('.data-table thead th')).map(th => th.textContent.trim()).join('\t');
            const csvContent = headers + '\n' + logs.join('\n');

            const blob = new Blob([csvContent], { type: 'text/csv' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'attendance-logs.csv';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        }

        // Search functionality
        document.getElementById('searchInput').addEventListener('input', function() {
            const searchTerm = this.value.toLowerCase();
            const rows = document.querySelectorAll('.data-table tbody tr');
            
            rows.forEach(row => {
                const text = row.textContent.toLowerCase();
                row.style.display = text.includes(searchTerm) ? '' : 'none';
            });
        });


    </script>

    <style>
        .filter-form {
            margin: 0;
        }

        .filter-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
            align-items: end;
        }

        .filter-group {
            display: flex;
            flex-direction: column;
            gap: 0.5rem;
        }

        .filter-group label {
            font-weight: 600;
            color: var(--text-secondary);
            font-size: 0.875rem;
        }

        .form-control {
            padding: 0.75rem;
            border: 1px solid var(--border-primary);
            border-radius: 6px;
            background: var(--bg-primary);
            color: var(--text-primary);
            font-size: 0.875rem;
        }

        .form-control:focus {
            outline: none;
            border-color: var(--primary);
            box-shadow: 0 0 0 3px rgba(var(--primary-rgb), 0.1);
        }

        .training-day-card {
            margin-bottom: 2rem;
        }

        .training-day-card .card-header {
            background: linear-gradient(135deg, var(--primary), var(--primary-dark));
            color: white;
        }

        .training-day-card .card-header h3 {
            color: white;
        }

        @media (max-width: 768px) {
            .filter-grid {
                grid-template-columns: 1fr;
            }
        }


    </style>
</body>
</html>