<?php
require_once '../includes/session.php';
require_once '../includes/db.php';
check_login();

// Access control: Allow admins, instructors, officers, and higher ranks
if(!in_array($_SESSION['role'], ['admin', 'instructor', 'officer', '1cl', '2cl', 'commandant'])){
    die('Access Denied. You do not have permission to create announcements.');
}

// Get recent announcements count for statistics
$recent_announcements_sql = "SELECT COUNT(*) as total FROM announcements WHERE created_at >= DATE_SUB(NOW(), INTERVAL 7 DAY)";
$recent_announcements_result = mysqli_query($link, $recent_announcements_sql);
$recent_announcements = mysqli_fetch_assoc($recent_announcements_result)['total'] ?? 0;

$total_announcements_sql = "SELECT COUNT(*) as total FROM announcements";
$total_announcements_result = mysqli_query($link, $total_announcements_sql);
$total_announcements = mysqli_fetch_assoc($total_announcements_result)['total'] ?? 0;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Announcement - ROTC Management System</title>
    <link rel="stylesheet" href="../css/tactical-theme.css">
    <link rel="stylesheet" href="../css/dashboard-unified.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>

<body data-role="<?php echo $_SESSION['role']; ?>">
    <div class="dashboard-container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <div class="sidebar-header">
                <div class="logo">
                    <div class="logo-icon"><i class="fas fa-bullhorn"></i></div>
                    <span>Create Announcement</span>
                </div>
            </div>
            
            <nav class="sidebar-nav">
                <div class="nav-menu">
                    <!-- Navigation will be generated by JavaScript -->
                </div>
            </nav>
        </aside>

        <!-- Main Content -->
        <main class="main-content">
            <!-- Header -->
            <header class="header">
                <div class="header-left">
                    <button class="sidebar-toggle">
                        <i class="fas fa-bars"></i>
                    </button>
                    <h1 class="page-title">Create Announcement</h1>
                </div>
                
                <div class="header-right">
                    <div class="header-actions">
                        <button class="action-btn" onclick="previewAnnouncement()" title="Preview">
                            <i class="fas fa-eye"></i>
                        </button>
                        <button class="action-btn" onclick="saveDraft()" title="Save Draft">
                            <i class="fas fa-save"></i>
                        </button>
                        <div class="user-menu">
                            <div class="user-avatar">
                                <i class="fas fa-user"></i>
                                <span class="user-name"><?php echo htmlspecialchars($_SESSION['full_name']); ?></span>
                                <i class="fas fa-chevron-down"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <!-- Content Area -->
            <div class="content-area">
                <!-- Statistics -->
                <div class="stats-grid">
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-bullhorn"></i>
                        </div>
                        <div class="stat-content">
                            <div class="stat-number"><?php echo $total_announcements; ?></div>
                            <div class="stat-label">Total Announcements</div>
                        </div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-calendar-week"></i>
                        </div>
                        <div class="stat-content">
                            <div class="stat-number"><?php echo $recent_announcements; ?></div>
                            <div class="stat-label">This Week</div>
                        </div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-icon">
                            <i class="fas fa-user-edit"></i>
                        </div>
                        <div class="stat-content">
                            <div class="stat-number"><?php echo ucfirst($_SESSION['role']); ?></div>
                            <div class="stat-label">Your Role</div>
                        </div>
                    </div>
                </div>

                <?php if(isset($_GET['message'])): ?>
                    <div class="alert <?php echo ($_GET['status'] == 'success') ? 'alert-success' : 'alert-danger'; ?>">
                        <i class="fas <?php echo ($_GET['status'] == 'success') ? 'fa-check-circle' : 'fa-exclamation-triangle'; ?>"></i>
                        <?php echo htmlspecialchars($_GET['message']); ?>
                    </div>
                <?php endif; ?>

                <!-- Announcement Form -->
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-plus-circle"></i> Create New Announcement</h3>
                        <div class="card-actions">
                            <span class="badge badge-primary">New Post</span>
                        </div>
                    </div>
                    <div class="card-content">
                        <form action="process_announcement.php" method="post" class="announcement-form" id="announcementForm">
                            <div class="form-grid">
                                <div class="form-group full-width">
                                    <label for="title">
                                        <i class="fas fa-heading"></i> Announcement Title
                                    </label>
                                    <input type="text" name="title" id="title" class="form-control" 
                                           placeholder="Enter a clear and descriptive title..." 
                                           maxlength="200" required>
                                    <div class="form-help">Keep it concise and informative (max 200 characters)</div>
                                </div>

                                <div class="form-group">
                                    <label for="priority">
                                        <i class="fas fa-exclamation-circle"></i> Priority Level
                                    </label>
                                    <select name="priority" id="priority" class="form-control">
                                        <option value="normal">📢 Normal</option>
                                        <option value="important">⚠️ Important</option>
                                        <option value="urgent">🚨 Urgent</option>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="category">
                                        <i class="fas fa-tags"></i> Category
                                    </label>
                                    <select name="category" id="category" class="form-control">
                                        <option value="general">📋 General</option>
                                        <option value="training">🎯 Training</option>
                                        <option value="event">📅 Event</option>
                                        <option value="academic">🎓 Academic</option>
                                        <option value="administrative">📊 Administrative</option>
                                    </select>
                                </div>

                                <div class="form-group full-width">
                                    <label for="content">
                                        <i class="fas fa-align-left"></i> Announcement Content
                                    </label>
                                    <div class="editor-toolbar">
                                        <button type="button" class="editor-btn" onclick="formatText('bold')" title="Bold">
                                            <i class="fas fa-bold"></i>
                                        </button>
                                        <button type="button" class="editor-btn" onclick="formatText('italic')" title="Italic">
                                            <i class="fas fa-italic"></i>
                                        </button>
                                        <button type="button" class="editor-btn" onclick="formatText('underline')" title="Underline">
                                            <i class="fas fa-underline"></i>
                                        </button>
                                        <button type="button" class="editor-btn" onclick="insertList()" title="Bullet List">
                                            <i class="fas fa-list-ul"></i>
                                        </button>
                                    </div>
                                    <textarea name="content" id="content" class="form-control content-editor" 
                                              rows="8" placeholder="Write your announcement content here..." required></textarea>
                                    <div class="form-help">
                                        <span id="charCount">0</span> characters | Use clear and professional language
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="target_audience">
                                        <i class="fas fa-users"></i> Target Audience
                                    </label>
                                    <select name="target_audience" id="target_audience" class="form-control">
                                        <option value="all">👥 All Personnel</option>
                                        <option value="cadets">🎓 Cadets Only</option>
                                        <option value="officers">⭐ Officers Only</option>
                                        <option value="instructors">👨‍🏫 Instructors Only</option>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="expires_at">
                                        <i class="fas fa-calendar-times"></i> Expiration Date (Optional)
                                    </label>
                                    <input type="datetime-local" name="expires_at" id="expires_at" class="form-control">
                                    <div class="form-help">Leave empty for permanent announcement</div>
                                </div>
                            </div>

                            <div class="form-actions">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fas fa-bullhorn"></i> Publish Announcement
                                </button>
                                <button type="button" class="btn btn-outline" onclick="saveDraft()">
                                    <i class="fas fa-save"></i> Save as Draft
                                </button>
                                <button type="button" class="btn btn-secondary" onclick="resetForm()">
                                    <i class="fas fa-undo"></i> Reset Form
                                </button>
                            </div>
                        </form>
                    </div>
                </div>

                <!-- Preview Modal -->
                <div id="previewModal" class="modal" style="display: none;">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h3><i class="fas fa-eye"></i> Announcement Preview</h3>
                            <button type="button" class="modal-close" onclick="closePreview()">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div id="previewContent"></div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-outline" onclick="closePreview()">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <script src="../js/dashboard-unified.js"></script>

    <script>
        // Character counter
        document.getElementById('content').addEventListener('input', function() {
            const charCount = this.value.length;
            document.getElementById('charCount').textContent = charCount;
        });

        // Form validation
        document.getElementById('announcementForm').addEventListener('submit', function(e) {
            const title = document.getElementById('title').value.trim();
            const content = document.getElementById('content').value.trim();
            
            if (title.length < 5) {
                e.preventDefault();
                alert('Title must be at least 5 characters long.');
                return;
            }
            
            if (content.length < 10) {
                e.preventDefault();
                alert('Content must be at least 10 characters long.');
                return;
            }
        });

        // Preview function
        function previewAnnouncement() {
            const title = document.getElementById('title').value;
            const content = document.getElementById('content').value;
            const priority = document.getElementById('priority').value;
            const category = document.getElementById('category').value;
            
            if (!title || !content) {
                alert('Please fill in title and content to preview.');
                return;
            }
            
            const previewHTML = `
                <div class="announcement-preview">
                    <div class="announcement-header">
                        <h4>${title}</h4>
                        <div class="announcement-meta">
                            <span class="badge badge-${priority}">${priority.toUpperCase()}</span>
                            <span class="badge badge-secondary">${category}</span>
                        </div>
                    </div>
                    <div class="announcement-content">
                        ${content.replace(/\n/g, '<br>')}
                    </div>
                    <div class="announcement-footer">
                        <small>Posted by: ${document.querySelector('.user-name').textContent}</small>
                        <small>Date: ${new Date().toLocaleDateString()}</small>
                    </div>
                </div>
            `;
            
            document.getElementById('previewContent').innerHTML = previewHTML;
            document.getElementById('previewModal').style.display = 'flex';
        }

        // Close preview
        function closePreview() {
            document.getElementById('previewModal').style.display = 'none';
        }

        // Save draft function
        function saveDraft() {
            const formData = new FormData(document.getElementById('announcementForm'));
            formData.append('save_draft', '1');
            
            // Here you would typically send to a draft endpoint
            alert('Draft saved locally! (Feature to be implemented)');
        }

        // Reset form
        function resetForm() {
            if (confirm('Are you sure you want to reset the form? All content will be lost.')) {
                document.getElementById('announcementForm').reset();
                document.getElementById('charCount').textContent = '0';
            }
        }

        // Text formatting functions
        function formatText(command) {
            const textarea = document.getElementById('content');
            const start = textarea.selectionStart;
            const end = textarea.selectionEnd;
            const selectedText = textarea.value.substring(start, end);
            
            if (selectedText) {
                let formattedText = '';
                switch(command) {
                    case 'bold':
                        formattedText = `**${selectedText}**`;
                        break;
                    case 'italic':
                        formattedText = `*${selectedText}*`;
                        break;
                    case 'underline':
                        formattedText = `__${selectedText}__`;
                        break;
                }
                
                textarea.value = textarea.value.substring(0, start) + formattedText + textarea.value.substring(end);
                textarea.focus();
            }
        }

        function insertList() {
            const textarea = document.getElementById('content');
            const cursorPos = textarea.selectionStart;
            const textBefore = textarea.value.substring(0, cursorPos);
            const textAfter = textarea.value.substring(cursorPos);
            
            const listText = '\n• Item 1\n• Item 2\n• Item 3\n';
            textarea.value = textBefore + listText + textAfter;
            textarea.focus();
        }

        // Auto-save functionality (every 30 seconds)
        setInterval(function() {
            const title = document.getElementById('title').value;
            const content = document.getElementById('content').value;
            
            if (title || content) {
                localStorage.setItem('announcement_draft', JSON.stringify({
                    title: title,
                    content: content,
                    timestamp: new Date().toISOString()
                }));
            }
        }, 30000);

        // Load draft on page load
        window.addEventListener('load', function() {
            const draft = localStorage.getItem('announcement_draft');
            if (draft) {
                const draftData = JSON.parse(draft);
                const draftAge = new Date() - new Date(draftData.timestamp);
                
                // Only load draft if it's less than 24 hours old
                if (draftAge < 24 * 60 * 60 * 1000) {
                    if (confirm('A draft was found. Would you like to restore it?')) {
                        document.getElementById('title').value = draftData.title;
                        document.getElementById('content').value = draftData.content;
                        document.getElementById('charCount').textContent = draftData.content.length;
                    }
                }
            }
        });
    </script>

    <style>
        .announcement-form {
            margin: 0;
        }

        .form-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 1.5rem;
            margin-bottom: 2rem;
        }

        .form-group.full-width {
            grid-column: 1 / -1;
        }

        .form-group {
            display: flex;
            flex-direction: column;
            gap: 0.5rem;
        }

        .form-group label {
            font-weight: 600;
            color: var(--text-secondary);
            font-size: 0.875rem;
            display: flex;
            align-items: center;
            gap: 0.5rem;
        }

        .form-control {
            padding: 0.75rem;
            border: 1px solid var(--border-primary);
            border-radius: 6px;
            background: var(--bg-primary);
            color: var(--text-primary);
            font-size: 0.875rem;
            transition: all 0.2s ease;
        }

        .form-control:focus {
            outline: none;
            border-color: var(--primary);
            box-shadow: 0 0 0 3px rgba(var(--primary-rgb), 0.1);
        }

        .content-editor {
            min-height: 200px;
            font-family: inherit;
            resize: vertical;
        }

        .editor-toolbar {
            display: flex;
            gap: 0.5rem;
            margin-bottom: 0.5rem;
            padding: 0.5rem;
            background: var(--bg-secondary);
            border-radius: 6px;
            border: 1px solid var(--border-primary);
        }

        .editor-btn {
            padding: 0.5rem;
            border: none;
            background: transparent;
            color: var(--text-secondary);
            border-radius: 4px;
            cursor: pointer;
            transition: all 0.2s ease;
        }

        .editor-btn:hover {
            background: var(--primary);
            color: white;
        }

        .form-help {
            font-size: 0.75rem;
            color: var(--text-secondary);
            margin-top: 0.25rem;
        }

        .form-actions {
            display: flex;
            gap: 1rem;
            justify-content: flex-start;
            padding-top: 1rem;
            border-top: 1px solid var(--border-primary);
        }

        .modal {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.5);
            display: flex;
            align-items: center;
            justify-content: center;
            z-index: 1000;
        }

        .modal-content {
            background: var(--bg-primary);
            border-radius: 8px;
            max-width: 600px;
            width: 90%;
            max-height: 80vh;
            overflow-y: auto;
        }

        .modal-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 1rem;
            border-bottom: 1px solid var(--border-primary);
        }

        .modal-body {
            padding: 1rem;
        }

        .modal-footer {
            padding: 1rem;
            border-top: 1px solid var(--border-primary);
            text-align: right;
        }

        .modal-close {
            background: none;
            border: none;
            font-size: 1.2rem;
            cursor: pointer;
            color: var(--text-secondary);
        }

        .announcement-preview {
            border: 1px solid var(--border-primary);
            border-radius: 6px;
            padding: 1rem;
        }

        .announcement-header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            margin-bottom: 1rem;
        }

        .announcement-meta {
            display: flex;
            gap: 0.5rem;
        }

        .announcement-content {
            margin-bottom: 1rem;
            line-height: 1.6;
        }

        .announcement-footer {
            display: flex;
            justify-content: space-between;
            font-size: 0.75rem;
            color: var(--text-secondary);
            border-top: 1px solid var(--border-primary);
            padding-top: 0.5rem;
        }

        @media (max-width: 768px) {
            .form-grid {
                grid-template-columns: 1fr;
            }
            
            .form-actions {
                flex-direction: column;
            }
            
            .editor-toolbar {
                flex-wrap: wrap;
            }
        }
    </style>
</body>
</html>
