<?php
require_once '../includes/session.php';
require_once '../includes/db.php';
check_login();

$sql = "SELECT a.title, a.content, a.created_at, u.username as author_name
        FROM announcements a
        JOIN users u ON a.author_id = u.id
        ORDER BY a.created_at DESC";

$announcements = [];
if($result = mysqli_query($link, $sql)){
    while($row = mysqli_fetch_assoc($result)){
        $announcements[] = $row;
    }
}

mysqli_close($link);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Announcements - ROTC Management System</title>
    <link rel="stylesheet" href="../css/tactical-theme.css">
    <link rel="stylesheet" href="../css/dashboard-unified.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>

<body data-role="<?php echo $_SESSION['role']; ?>">
    <div class="dashboard-container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <div class="sidebar-header">
                <div class="logo">
                    <div class="logo-icon"><i class="fas fa-bullhorn"></i></div>
                    <span>Announcements</span>
                </div>
            </div>
            
            <nav class="sidebar-nav">
                <div class="nav-menu">
                    <!-- Navigation will be generated by JavaScript -->
                </div>
            </nav>
        </aside>

        <!-- Main Content -->
        <main class="main-content">
            <!-- Header -->
            <header class="header">
                <div class="header-left">
                    <button class="sidebar-toggle">
                        <i class="fas fa-bars"></i>
                    </button>
                    <h1 class="page-title">Announcements</h1>
                </div>
                
                <div class="header-center">
                    <div class="search-container">
                        <i class="fas fa-search search-icon"></i>
                        <input type="text" placeholder="Search announcements..." class="search-input" id="announcementSearch">
                    </div>
                </div>
                
                <div class="header-right">
                    <div class="header-actions">
                        <?php if (in_array($_SESSION['role'], ['admin', 'instructor', 'officer'])): ?>
                            <button class="action-btn" onclick="window.location.href='create.php'" title="Create Announcement">
                                <i class="fas fa-plus"></i>
                            </button>
                        <?php endif; ?>
                        <div class="user-menu">
                            <div class="user-avatar">
                                <i class="fas fa-user"></i>
                                <span class="user-name"><?php echo htmlspecialchars($_SESSION['full_name']); ?></span>
                                <i class="fas fa-chevron-down"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <!-- Content Area -->
            <div class="content-area">
                <!-- Announcements List -->
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-bullhorn"></i> Recent Announcements</h3>
                        <div class="card-actions">
                            <select class="form-select" id="filterPeriod">
                                <option value="">All Time</option>
                                <option value="7">Last 7 Days</option>
                                <option value="30">Last 30 Days</option>
                                <option value="90">Last 3 Months</option>
                            </select>
                        </div>
                    </div>
                    <div class="card-content">
                        <?php if (empty($announcements)): ?>
                            <div class="empty-state">
                                <i class="fas fa-bullhorn"></i>
                                <h4>No Announcements</h4>
                                <p>No announcements have been posted yet.</p>
                                <?php if (in_array($_SESSION['role'], ['admin', 'instructor', 'officer'])): ?>
                                    <button class="btn btn-primary" onclick="window.location.href='create.php'">
                                        <i class="fas fa-plus"></i> Create First Announcement
                                    </button>
                                <?php endif; ?>
                            </div>
                        <?php else: ?>
                            <div class="announcements-list">
                                <?php foreach ($announcements as $announcement): ?>
                                    <div class="announcement-card" data-date="<?php echo $announcement['created_at']; ?>">
                                        <div class="announcement-header">
                                            <h4 class="announcement-title"><?php echo htmlspecialchars($announcement['title']); ?></h4>
                                            <div class="announcement-meta">
                                                <span class="author">
                                                    <i class="fas fa-user"></i>
                                                    <?php echo htmlspecialchars($announcement['author_name']); ?>
                                                </span>
                                                <span class="date">
                                                    <i class="fas fa-clock"></i>
                                                    <?php echo date('M d, Y \\a\\t g:i A', strtotime($announcement['created_at'])); ?>
                                                </span>
                                            </div>
                                        </div>
                                        <div class="announcement-content">
                                            <?php echo nl2br(htmlspecialchars($announcement['content'])); ?>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <script src="../js/dashboard-unified.js"></script>
    <script>
        // Search functionality
        document.getElementById('announcementSearch').addEventListener('input', function(e) {
            const searchTerm = e.target.value.toLowerCase();
            const announcements = document.querySelectorAll('.announcement-card');
            
            announcements.forEach(announcement => {
                const text = announcement.textContent.toLowerCase();
                announcement.style.display = text.includes(searchTerm) ? '' : 'none';
            });
        });

        // Filter by period
        document.getElementById('filterPeriod').addEventListener('change', function(e) {
            const days = parseInt(e.target.value);
            const announcements = document.querySelectorAll('.announcement-card');
            
            if (!days) {
                announcements.forEach(announcement => announcement.style.display = '');
                return;
            }
            
            const cutoffDate = new Date();
            cutoffDate.setDate(cutoffDate.getDate() - days);
            
            announcements.forEach(announcement => {
                const dateStr = announcement.dataset.date;
                const announcementDate = new Date(dateStr);
                announcement.style.display = announcementDate >= cutoffDate ? '' : 'none';
            });
        });
    </script>

    <style>
        .announcements-list {
            display: flex;
            flex-direction: column;
            gap: 1.5rem;
        }

        .announcement-card {
            background: var(--card-bg);
            border: 1px solid var(--border-primary);
            border-radius: 8px;
            padding: 1.5rem;
            transition: all var(--transition-fast);
        }

        .announcement-card:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
            border-color: var(--primary);
        }

        .announcement-header {
            margin-bottom: 1rem;
        }

        .announcement-title {
            margin: 0 0 0.5rem 0;
            color: var(--text-primary);
            font-size: 1.25rem;
            font-weight: 600;
        }

        .announcement-meta {
            display: flex;
            gap: 1.5rem;
            font-size: 0.875rem;
            color: var(--text-secondary);
        }

        .announcement-meta span {
            display: flex;
            align-items: center;
            gap: 0.5rem;
        }

        .announcement-content {
            color: var(--text-primary);
            line-height: 1.6;
            white-space: pre-line;
        }

        @media (max-width: 768px) {
            .announcement-meta {
                flex-direction: column;
                gap: 0.5rem;
            }
        }
    </style>
</body>
</html>
