<?php
require_once 'includes/session.php';
require_once 'includes/db.php';

// Cadet-only access
check_login();
if (!in_array($_SESSION['role'], ['cadet', 'basic_cadet'])) {
    redirect_to_dashboard();
}

// Fetch cadet's full profile data
$user_id = $_SESSION['id'];
$sql = "SELECT cp.*, u.email, u.username 
        FROM cadet_profiles cp 
        JOIN users u ON cp.user_id = u.id 
        WHERE cp.user_id = ?";
$stmt = $link->prepare($sql);
$stmt->bind_param("i", $user_id);
$stmt->execute();
$result = $stmt->get_result();
$profile_data = $result->fetch_assoc();
$stmt->close();
$link->close();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Profile - ROTC Management System</title>
    <link rel="stylesheet" href="css/tactical-theme.css">
    <link rel="stylesheet" href="css/dashboard-unified.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>

<body data-role="cadet">
    <div class="dashboard-container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <div class="sidebar-header">
                <div class="logo">
                    <div class="logo-icon"><i class="fas fa-user"></i></div>
                    <span>My Profile</span>
                </div>
            </div>
            
            <nav class="sidebar-nav">
                <div class="nav-menu">
                    <!-- Navigation will be generated by JavaScript -->
                </div>
            </nav>
        </aside>

        <!-- Main Content -->
        <main class="main-content">
            <!-- Header -->
            <header class="header">
                <div class="header-left">
                    <button class="sidebar-toggle">
                        <i class="fas fa-bars"></i>
                    </button>
                    <h1 class="page-title">My Profile</h1>
                </div>
                
                <div class="header-right">
                    <div class="header-actions">
                        <button class="action-btn" onclick="window.print()" title="Print Profile">
                            <i class="fas fa-print"></i>
                        </button>
                        <div class="user-menu">
                            <div class="user-avatar">
                                <i class="fas fa-user"></i>
                                <span class="user-name"><?php echo htmlspecialchars($_SESSION['full_name']); ?></span>
                                <i class="fas fa-chevron-down"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <!-- Content Area -->
            <div class="content-area">
                <?php if ($profile_data): ?>
                    <!-- Profile Header -->
                    <div class="profile-header">
                        <div class="profile-photo">
                            <?php if (!empty($profile_data['photo_path']) && file_exists($profile_data['photo_path'])): ?>
                                <img src="<?php echo htmlspecialchars($profile_data['photo_path']); ?>" alt="Profile Photo" class="profile-image">
                            <?php else: ?>
                                <div class="profile-placeholder">
                                    <i class="fas fa-user"></i>
                                </div>
                            <?php endif; ?>
                        </div>
                        <div class="profile-info">
                            <h2><?php echo htmlspecialchars($profile_data['first_name'] . ' ' . $profile_data['last_name']); ?></h2>
                            <p class="profile-subtitle"><?php echo htmlspecialchars($profile_data['student_id']); ?> • <?php echo htmlspecialchars($profile_data['platoon']); ?> Platoon</p>
                            <div class="profile-badges">
                                <span class="badge badge-primary">Cadet</span>
                                <span class="badge badge-secondary"><?php echo htmlspecialchars($profile_data['course']); ?></span>
                            </div>
                        </div>
                        <div class="profile-qr">
                            <?php if (!empty($profile_data['qr_code_path']) && file_exists($profile_data['qr_code_path'])): ?>
                                <img src="<?php echo htmlspecialchars($profile_data['qr_code_path']); ?>" alt="QR Code" class="qr-code">
                                <p class="qr-label">My QR Code</p>
                            <?php else: ?>
                                <div class="qr-placeholder">
                                    <i class="fas fa-qrcode"></i>
                                    <p>QR Code Not Available</p>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>

                    <!-- Profile Details Grid -->
                    <div class="profile-grid">
                        <!-- Personal Information -->
                        <div class="content-card">
                            <div class="card-header">
                                <h3><i class="fas fa-user"></i> Personal Information</h3>
                            </div>
                            <div class="card-content">
                                <div class="info-grid">
                                    <div class="info-item">
                                        <label>Full Name</label>
                                        <span><?php echo htmlspecialchars($profile_data['first_name'] . ' ' . $profile_data['middle_name'] . ' ' . $profile_data['last_name']); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>Email Address</label>
                                        <span><?php echo htmlspecialchars($profile_data['email']); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>Contact Number</label>
                                        <span><?php echo htmlspecialchars($profile_data['contact_number'] ?? 'Not provided'); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>Date of Birth</label>
                                        <span><?php echo $profile_data['date_of_birth'] ? date('F d, Y', strtotime($profile_data['date_of_birth'])) : 'Not provided'; ?></span>
                                    </div>
                                    <div class="info-item full-width">
                                        <label>Address</label>
                                        <span><?php echo htmlspecialchars($profile_data['address'] ?? 'Not provided'); ?></span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Academic Information -->
                        <div class="content-card">
                            <div class="card-header">
                                <h3><i class="fas fa-graduation-cap"></i> Academic Information</h3>
                            </div>
                            <div class="card-content">
                                <div class="info-grid">
                                    <div class="info-item">
                                        <label>Student ID</label>
                                        <span><?php echo htmlspecialchars($profile_data['student_id']); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>School</label>
                                        <span><?php echo htmlspecialchars($profile_data['school'] ?? 'Not provided'); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>Course/Program</label>
                                        <span><?php echo htmlspecialchars($profile_data['course'] ?? 'Not provided'); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>Platoon</label>
                                        <span><?php echo htmlspecialchars($profile_data['platoon'] ?? 'Not assigned'); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>Year Level</label>
                                        <span><?php echo htmlspecialchars($profile_data['year_level'] ?? 'Not provided'); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>Section</label>
                                        <span><?php echo htmlspecialchars($profile_data['section'] ?? 'Not provided'); ?></span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Emergency Contact -->
                        <div class="content-card">
                            <div class="card-header">
                                <h3><i class="fas fa-phone"></i> Emergency Contact</h3>
                            </div>
                            <div class="card-content">
                                <div class="info-grid">
                                    <div class="info-item">
                                        <label>Contact Name</label>
                                        <span><?php echo htmlspecialchars($profile_data['emergency_contact_name'] ?? 'Not provided'); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>Contact Number</label>
                                        <span><?php echo htmlspecialchars($profile_data['emergency_contact_number'] ?? 'Not provided'); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>Relationship</label>
                                        <span><?php echo htmlspecialchars($profile_data['emergency_contact_relationship'] ?? 'Not provided'); ?></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php else: ?>
                    <div class="empty-state">
                        <i class="fas fa-exclamation-triangle"></i>
                        <h4>Profile Not Found</h4>
                        <p>Your profile information could not be retrieved. Please contact your administrator.</p>
                    </div>
                <?php endif; ?>
            </div>
        </main>
    </div>

    <script src="js/dashboard-unified.js"></script>

    <style>
        .profile-header {
            display: flex;
            align-items: center;
            gap: 2rem;
            padding: 2rem;
            background: var(--card-bg);
            border-radius: 12px;
            margin-bottom: 2rem;
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
        }

        .profile-photo {
            flex-shrink: 0;
        }

        .profile-image {
            width: 120px;
            height: 120px;
            border-radius: 50%;
            object-fit: cover;
            border: 4px solid var(--primary);
        }

        .profile-placeholder {
            width: 120px;
            height: 120px;
            border-radius: 50%;
            background: var(--bg-tertiary);
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 3rem;
            color: var(--text-muted);
            border: 4px solid var(--border-primary);
        }

        .profile-info {
            flex: 1;
        }

        .profile-info h2 {
            margin: 0 0 0.5rem 0;
            color: var(--text-primary);
            font-size: 2rem;
        }

        .profile-subtitle {
            color: var(--text-secondary);
            margin: 0 0 1rem 0;
            font-size: 1.1rem;
        }

        .profile-badges {
            display: flex;
            gap: 0.5rem;
        }

        .badge {
            padding: 0.25rem 0.75rem;
            border-radius: 20px;
            font-size: 0.875rem;
            font-weight: 500;
        }

        .badge-primary {
            background: var(--primary);
            color: white;
        }

        .badge-secondary {
            background: var(--bg-tertiary);
            color: var(--text-secondary);
        }

        .profile-qr {
            text-align: center;
            flex-shrink: 0;
        }

        .qr-code {
            width: 100px;
            height: 100px;
            border: 2px solid var(--border-primary);
            border-radius: 8px;
        }

        .qr-label {
            margin: 0.5rem 0 0 0;
            font-size: 0.875rem;
            color: var(--text-secondary);
        }

        .qr-placeholder {
            width: 100px;
            height: 100px;
            background: var(--bg-tertiary);
            border: 2px solid var(--border-primary);
            border-radius: 8px;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            color: var(--text-muted);
        }

        .qr-placeholder i {
            font-size: 2rem;
            margin-bottom: 0.5rem;
        }

        .qr-placeholder p {
            font-size: 0.75rem;
            margin: 0;
            text-align: center;
        }

        .profile-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
            gap: 2rem;
        }

        .info-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 1.5rem;
        }

        .info-item {
            display: flex;
            flex-direction: column;
            gap: 0.5rem;
        }

        .info-item.full-width {
            grid-column: 1 / -1;
        }

        .info-item label {
            font-weight: 600;
            color: var(--text-secondary);
            font-size: 0.875rem;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        .info-item span {
            color: var(--text-primary);
            font-size: 1rem;
        }

        @media (max-width: 768px) {
            .profile-header {
                flex-direction: column;
                text-align: center;
                gap: 1.5rem;
            }

            .profile-grid {
                grid-template-columns: 1fr;
            }

            .info-grid {
                grid-template-columns: 1fr;
            }
        }
    </style>
</body>
</html>
