<?php
require_once 'includes/session.php';
require_once 'includes/db.php';

// Officer and Instructor access
check_login();
if (!in_array($_SESSION['role'], ['instructor', 'officer', '1cl', '2cl', 'commandant'])) {
    redirect_to_dashboard();
}

// Get officer's platoon
$officer_platoon = $_SESSION['platoon'] ?? 'Unknown';

// Fetch cadets in the same platoon
$cadets = [];
$sql = "SELECT cp.*, u.username, u.email FROM cadet_profiles cp 
        JOIN users u ON cp.user_id = u.id 
        WHERE cp.platoon = ? ORDER BY cp.last_name, cp.first_name";
if ($stmt = $link->prepare($sql)) {
    $stmt->bind_param("s", $officer_platoon);
    $stmt->execute();
    $result = $stmt->get_result();
    while ($row = $result->fetch_assoc()) {
        $cadets[] = $row;
    }
    $stmt->close();
}

// Get platoon statistics
$total_cadets = count($cadets);
$active_cadets = 0;
$recent_attendance = 0;

// Count active cadets (those with recent activity)
$sql = "SELECT COUNT(DISTINCT cp.id) as active_count FROM cadet_profiles cp 
        JOIN users u ON cp.user_id = u.id 
        WHERE cp.platoon = ? AND u.created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)";
if ($stmt = $link->prepare($sql)) {
    $stmt->bind_param("s", $officer_platoon);
    $stmt->execute();
    $result = $stmt->get_result();
    if ($row = $result->fetch_assoc()) {
        $active_cadets = $row['active_count'];
    }
    $stmt->close();
}

$page_title = 'My Cadets';
include 'includes/header.php';
?>

<link rel="stylesheet" href="css/tactical-theme.css">
<link rel="stylesheet" href="css/dashboard-unified.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

<body data-role="<?php echo $_SESSION['role']; ?>">
    <div class="dashboard-container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <div class="sidebar-header">
                <div class="logo">
                    <div class="logo-icon"><i class="fas fa-users"></i></div>
                    <span>My Cadets</span>
                </div>
            </div>
            
            <nav class="sidebar-nav">
                <div class="nav-menu">
                    <!-- Navigation will be generated by JavaScript -->
                </div>
            </nav>
        </aside>

        <!-- Main Content -->
        <main class="main-content">
            <!-- Header -->
            <header class="header">
                <div class="header-left">
                    <button class="sidebar-toggle">
                        <i class="fas fa-bars"></i>
                    </button>
                    <h1 class="page-title">My Cadets - <?php echo htmlspecialchars($officer_platoon); ?></h1>
                </div>
                
                <div class="header-center">
                    <div class="search-container">
                        <i class="fas fa-search search-icon"></i>
                        <input type="text" placeholder="Search cadets..." class="search-input" id="cadetSearch">
                    </div>
                </div>
                
                <div class="header-right">
                    <div class="header-actions">
                        <button class="action-btn" title="Export List">
                            <i class="fas fa-download"></i>
                        </button>
                        <div class="user-menu">
                            <div class="user-avatar">
                                <i class="fas fa-user-tie"></i>
                                <span class="user-name"><?php echo htmlspecialchars($_SESSION['full_name']); ?></span>
                                <i class="fas fa-chevron-down"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <!-- Content Area -->
            <div class="content-area">
                <!-- Stats Cards -->
                <div class="stats-grid">
                    <div class="stat-card">
                        <div class="stat-header">
                            <div class="stat-icon">
                                <i class="fas fa-users"></i>
                            </div>
                        </div>
                        <div class="stat-content">
                            <div class="stat-value"><?php echo $total_cadets; ?></div>
                            <div class="stat-label">Total Cadets</div>
                            <div class="stat-change">In <?php echo htmlspecialchars($officer_platoon); ?></div>
                        </div>
                    </div>
                    
                    <div class="stat-card">
                        <div class="stat-header">
                            <div class="stat-icon">
                                <i class="fas fa-user-check"></i>
                            </div>
                        </div>
                        <div class="stat-content">
                            <div class="stat-value"><?php echo $active_cadets; ?></div>
                            <div class="stat-label">Active Cadets</div>
                            <div class="stat-change">Last 30 days</div>
                        </div>
                    </div>
                    
                    <div class="stat-card">
                        <div class="stat-header">
                            <div class="stat-icon">
                                <i class="fas fa-percentage"></i>
                            </div>
                        </div>
                        <div class="stat-content">
                            <div class="stat-value"><?php echo $total_cadets > 0 ? round(($active_cadets / $total_cadets) * 100) : 0; ?>%</div>
                            <div class="stat-label">Activity Rate</div>
                            <div class="stat-change">Engagement level</div>
                        </div>
                    </div>
                </div>

                <!-- Cadets Table -->
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-list"></i> Cadet Roster</h3>
                        <div class="card-actions">
                            <button class="btn btn-primary" onclick="window.location.href='attendance/dashboard.php'">
                                <i class="fas fa-calendar-check"></i> Take Attendance
                            </button>
                        </div>
                    </div>
                    <div class="card-content">
                        <?php if (empty($cadets)): ?>
                            <div class="empty-state">
                                <i class="fas fa-users-slash"></i>
                                <h4>No Cadets Found</h4>
                                <p>No cadets are currently assigned to <?php echo htmlspecialchars($officer_platoon); ?> platoon.</p>
                            </div>
                        <?php else: ?>
                            <div class="table-responsive">
                                <table class="data-table" id="cadetsTable">
                                    <thead>
                                        <tr>
                                            <th>Photo</th>
                                            <th>Name</th>
                                            <th>Student ID</th>
                                            <th>Email</th>
                                            <th>Year Level</th>
                                            <th>Course</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($cadets as $cadet): ?>
                                            <tr>
                                                <td>
                                                    <div class="cadet-photo">
                                                        <?php if (!empty($cadet['photo_path']) && file_exists('uploads/photos/' . $cadet['photo_path'])): ?>
                                                            <img src="uploads/photos/<?php echo htmlspecialchars($cadet['photo_path']); ?>" alt="Photo" class="profile-img">
                                                        <?php else: ?>
                                                            <div class="profile-placeholder">
                                                                <i class="fas fa-user"></i>
                                                            </div>
                                                        <?php endif; ?>
                                                    </div>
                                                </td>
                                                <td>
                                                    <div class="cadet-name">
                                                        <strong><?php echo htmlspecialchars($cadet['first_name'] . ' ' . $cadet['last_name']); ?></strong>
                                                        <small class="text-muted"><?php echo htmlspecialchars($cadet['username']); ?></small>
                                                    </div>
                                                </td>
                                                <td><?php echo htmlspecialchars($cadet['student_id'] ?? 'N/A'); ?></td>
                                                <td><?php echo htmlspecialchars($cadet['email']); ?></td>
                                                <td><?php echo htmlspecialchars($cadet['year_level'] ?? 'N/A'); ?></td>
                                                <td><?php echo htmlspecialchars($cadet['course'] ?? 'N/A'); ?></td>
                                                <td>
                                                    <div class="action-buttons">
                                                        <button class="btn btn-sm btn-outline" onclick="viewCadet(<?php echo $cadet['id']; ?>)" title="View Profile">
                                                            <i class="fas fa-eye"></i>
                                                        </button>
                                                        <button class="btn btn-sm btn-outline" onclick="window.location.href='grades/view_grades.php?cadet_id=<?php echo $cadet['id']; ?>'" title="View Grades">
                                                            <i class="fas fa-graduation-cap"></i>
                                                        </button>
                                                        <button class="btn btn-sm btn-outline" onclick="window.location.href='attendance/logs.php?cadet_id=<?php echo $cadet['id']; ?>'" title="View Attendance">
                                                            <i class="fas fa-calendar-check"></i>
                                                        </button>
                                                    </div>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <script src="js/dashboard-unified.js"></script>
    <script>
        // Search functionality
        document.getElementById('cadetSearch').addEventListener('input', function(e) {
            const searchTerm = e.target.value.toLowerCase();
            const rows = document.querySelectorAll('#cadetsTable tbody tr');
            
            rows.forEach(row => {
                const text = row.textContent.toLowerCase();
                row.style.display = text.includes(searchTerm) ? '' : 'none';
            });
        });

        function viewCadet(cadetId) {
            window.location.href = `view_profile.php?id=${cadetId}`;
        }
    </script>
</body>
</html>
