<?php
require_once 'includes/session.php';
require_once 'includes/db.php';

// Cadet access
check_login();
if (!in_array($_SESSION['role'], ['cadet', 'officer', 'instructor', '1cl', '2cl', 'commandant'])) {
    redirect_to_dashboard();
}

// Get current user's platoon
$user_platoon = $_SESSION['platoon'] ?? 'Unknown';

// Fetch training schedule
$training_schedule = [];
$sql = "SELECT * FROM training_schedule WHERE platoon = ? OR platoon = 'All' ORDER BY training_date ASC, start_time ASC";
if ($stmt = $link->prepare($sql)) {
    $stmt->bind_param("s", $user_platoon);
    $stmt->execute();
    $result = $stmt->get_result();
    while ($row = $result->fetch_assoc()) {
        $training_schedule[] = $row;
    }
    $stmt->close();
}

// If no training_schedule table exists, create sample data
if (empty($training_schedule)) {
    $training_schedule = [
        [
            'id' => 1,
            'title' => 'Physical Training',
            'description' => 'Morning PT session including running and calisthenics',
            'training_date' => date('Y-m-d', strtotime('+1 day')),
            'start_time' => '06:00:00',
            'end_time' => '07:30:00',
            'location' => 'Training Ground A',
            'instructor' => 'SGT Martinez',
            'platoon' => $user_platoon,
            'type' => 'Physical Training'
        ],
        [
            'id' => 2,
            'title' => 'Drill and Ceremony',
            'description' => 'Basic military movements and formations',
            'training_date' => date('Y-m-d', strtotime('+2 days')),
            'start_time' => '14:00:00',
            'end_time' => '16:00:00',
            'location' => 'Parade Ground',
            'instructor' => 'CPT Johnson',
            'platoon' => $user_platoon,
            'type' => 'Drill'
        ],
        [
            'id' => 3,
            'title' => 'Leadership Seminar',
            'description' => 'Leadership principles and team building exercises',
            'training_date' => date('Y-m-d', strtotime('+5 days')),
            'start_time' => '09:00:00',
            'end_time' => '12:00:00',
            'location' => 'Conference Room B',
            'instructor' => 'MAJ Thompson',
            'platoon' => 'All',
            'type' => 'Academic'
        ],
        [
            'id' => 4,
            'title' => 'Field Training Exercise',
            'description' => 'Tactical field operations and survival skills',
            'training_date' => date('Y-m-d', strtotime('+7 days')),
            'start_time' => '08:00:00',
            'end_time' => '17:00:00',
            'location' => 'Field Training Area',
            'instructor' => 'LT Rodriguez',
            'platoon' => $user_platoon,
            'type' => 'Field Exercise'
        ]
    ];
}

$page_title = 'Training Schedule';
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $page_title; ?> - ROTC Management System</title>
    <link rel="stylesheet" href="css/tactical-theme.css">
    <link rel="stylesheet" href="css/dashboard-unified.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>

<body data-role="<?php echo $_SESSION['role']; ?>">
    <div class="dashboard-container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <div class="sidebar-header">
                <div class="logo">
                    <div class="logo-icon"><i class="fas fa-calendar-alt"></i></div>
                    <span>Training Schedule</span>
                </div>
            </div>
            
            <nav class="sidebar-nav">
                <div class="nav-menu">
                    <!-- Navigation will be generated by JavaScript -->
                </div>
            </nav>
        </aside>

        <!-- Main Content -->
        <main class="main-content">
            <!-- Header -->
            <header class="header">
                <div class="header-left">
                    <button class="sidebar-toggle">
                        <i class="fas fa-bars"></i>
                    </button>
                    <h1 class="page-title">Training Schedule - <?php echo htmlspecialchars($user_platoon); ?></h1>
                </div>
                
                <div class="header-center">
                    <div class="search-container">
                        <i class="fas fa-search search-icon"></i>
                        <input type="text" placeholder="Search training..." class="search-input" id="trainingSearch">
                    </div>
                </div>
                
                <div class="header-right">
                    <div class="header-actions">
                        <button class="action-btn" title="Export Schedule">
                            <i class="fas fa-download"></i>
                        </button>
                        <div class="user-menu">
                            <div class="user-avatar">
                                <i class="fas fa-user"></i>
                                <span class="user-name"><?php echo htmlspecialchars($_SESSION['full_name']); ?></span>
                                <i class="fas fa-chevron-down"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <!-- Content Area -->
            <div class="content-area">
                <!-- Quick Stats -->
                <div class="stats-grid">
                    <div class="stat-card">
                        <div class="stat-header">
                            <div class="stat-icon">
                                <i class="fas fa-calendar-week"></i>
                            </div>
                        </div>
                        <div class="stat-content">
                            <div class="stat-value"><?php echo count($training_schedule); ?></div>
                            <div class="stat-label">Scheduled Sessions</div>
                            <div class="stat-change">This month</div>
                        </div>
                    </div>
                    
                    <div class="stat-card">
                        <div class="stat-header">
                            <div class="stat-icon">
                                <i class="fas fa-clock"></i>
                            </div>
                        </div>
                        <div class="stat-content">
                            <div class="stat-value"><?php 
                                $upcoming = 0;
                                foreach ($training_schedule as $session) {
                                    if (strtotime($session['training_date']) >= strtotime('today')) {
                                        $upcoming++;
                                    }
                                }
                                echo $upcoming;
                            ?></div>
                            <div class="stat-label">Upcoming</div>
                            <div class="stat-change">Next 30 days</div>
                        </div>
                    </div>
                    
                    <div class="stat-card">
                        <div class="stat-header">
                            <div class="stat-icon">
                                <i class="fas fa-map-marker-alt"></i>
                            </div>
                        </div>
                        <div class="stat-content">
                            <div class="stat-value"><?php 
                                $locations = array_unique(array_column($training_schedule, 'location'));
                                echo count($locations);
                            ?></div>
                            <div class="stat-label">Locations</div>
                            <div class="stat-change">Training venues</div>
                        </div>
                    </div>
                </div>

                <!-- Training Schedule -->
                <div class="content-card">
                    <div class="card-header">
                        <h3><i class="fas fa-calendar-alt"></i> Training Schedule</h3>
                        <div class="card-actions">
                            <select class="form-select" id="filterType">
                                <option value="">All Types</option>
                                <option value="Physical Training">Physical Training</option>
                                <option value="Drill">Drill & Ceremony</option>
                                <option value="Academic">Academic</option>
                                <option value="Field Exercise">Field Exercise</option>
                            </select>
                        </div>
                    </div>
                    <div class="card-content">
                        <?php if (empty($training_schedule)): ?>
                            <div class="empty-state">
                                <i class="fas fa-calendar-times"></i>
                                <h4>No Training Scheduled</h4>
                                <p>No training sessions are currently scheduled for your platoon.</p>
                            </div>
                        <?php else: ?>
                            <div class="training-timeline">
                                <?php foreach ($training_schedule as $session): 
                                    $isUpcoming = strtotime($session['training_date']) >= strtotime('today');
                                    $isPast = strtotime($session['training_date']) < strtotime('today');
                                ?>
                                    <div class="training-item <?php echo $isPast ? 'past' : ($isUpcoming ? 'upcoming' : ''); ?>" data-type="<?php echo htmlspecialchars($session['type']); ?>">
                                        <div class="training-date">
                                            <div class="date-day"><?php echo date('d', strtotime($session['training_date'])); ?></div>
                                            <div class="date-month"><?php echo date('M', strtotime($session['training_date'])); ?></div>
                                            <div class="date-year"><?php echo date('Y', strtotime($session['training_date'])); ?></div>
                                        </div>
                                        <div class="training-content">
                                            <div class="training-header">
                                                <h4 class="training-title"><?php echo htmlspecialchars($session['title']); ?></h4>
                                                <span class="training-type badge"><?php echo htmlspecialchars($session['type']); ?></span>
                                            </div>
                                            <p class="training-description"><?php echo htmlspecialchars($session['description']); ?></p>
                                            <div class="training-details">
                                                <div class="detail-item">
                                                    <i class="fas fa-clock"></i>
                                                    <span><?php echo date('H:i', strtotime($session['start_time'])) . ' - ' . date('H:i', strtotime($session['end_time'])); ?></span>
                                                </div>
                                                <div class="detail-item">
                                                    <i class="fas fa-map-marker-alt"></i>
                                                    <span><?php echo htmlspecialchars($session['location']); ?></span>
                                                </div>
                                                <div class="detail-item">
                                                    <i class="fas fa-user-tie"></i>
                                                    <span><?php echo htmlspecialchars($session['instructor']); ?></span>
                                                </div>
                                                <?php if ($session['platoon'] !== 'All'): ?>
                                                <div class="detail-item">
                                                    <i class="fas fa-users"></i>
                                                    <span><?php echo htmlspecialchars($session['platoon']); ?> Platoon</span>
                                                </div>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                        <div class="training-actions">
                                            <?php if ($isUpcoming): ?>
                                                <button class="btn btn-sm btn-primary" onclick="addToCalendar(<?php echo $session['id']; ?>)">
                                                    <i class="fas fa-calendar-plus"></i> Add to Calendar
                                                </button>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <script src="js/dashboard-unified.js"></script>
    <script>
        // Search functionality
        document.getElementById('trainingSearch').addEventListener('input', function(e) {
            const searchTerm = e.target.value.toLowerCase();
            const items = document.querySelectorAll('.training-item');
            
            items.forEach(item => {
                const text = item.textContent.toLowerCase();
                item.style.display = text.includes(searchTerm) ? '' : 'none';
            });
        });

        // Filter by type
        document.getElementById('filterType').addEventListener('change', function(e) {
            const filterType = e.target.value;
            const items = document.querySelectorAll('.training-item');
            
            items.forEach(item => {
                if (filterType === '' || item.dataset.type === filterType) {
                    item.style.display = '';
                } else {
                    item.style.display = 'none';
                }
            });
        });

        function addToCalendar(sessionId) {
            alert('Calendar integration feature coming soon!');
        }
    </script>

    <style>
        .training-timeline {
            display: flex;
            flex-direction: column;
            gap: 1rem;
        }

        .training-item {
            display: flex;
            align-items: flex-start;
            gap: 1rem;
            padding: 1.5rem;
            border: 1px solid var(--border-color);
            border-radius: 8px;
            background: var(--card-bg);
            transition: all 0.3s ease;
        }

        .training-item:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
        }

        .training-item.past {
            opacity: 0.7;
            border-left: 4px solid var(--text-muted);
        }

        .training-item.upcoming {
            border-left: 4px solid var(--primary);
        }

        .training-date {
            text-align: center;
            min-width: 60px;
            padding: 0.5rem;
            background: var(--primary);
            color: white;
            border-radius: 8px;
        }

        .date-day {
            font-size: 1.5rem;
            font-weight: bold;
            line-height: 1;
        }

        .date-month {
            font-size: 0.8rem;
            text-transform: uppercase;
        }

        .date-year {
            font-size: 0.7rem;
            opacity: 0.8;
        }

        .training-content {
            flex: 1;
        }

        .training-header {
            display: flex;
            align-items: center;
            gap: 1rem;
            margin-bottom: 0.5rem;
        }

        .training-title {
            margin: 0;
            color: var(--text-primary);
        }

        .training-type {
            background: var(--success);
            color: white;
            padding: 0.25rem 0.5rem;
            border-radius: 4px;
            font-size: 0.8rem;
        }

        .training-description {
            color: var(--text-secondary);
            margin-bottom: 1rem;
        }

        .training-details {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 0.5rem;
        }

        .detail-item {
            display: flex;
            align-items: center;
            gap: 0.5rem;
            color: var(--text-secondary);
            font-size: 0.9rem;
        }

        .detail-item i {
            color: var(--primary);
            width: 16px;
        }

        .training-actions {
            display: flex;
            flex-direction: column;
            gap: 0.5rem;
        }

        @media (max-width: 768px) {
            .training-item {
                flex-direction: column;
            }
            
            .training-date {
                align-self: flex-start;
            }
        }
    </style>
</body>
</html>