<?php
require_once 'includes/session.php';
require_once 'includes/db.php';
require_once 'includes/SecurityLogger.php';

// Admin-only access
check_login();
if ($_SESSION['role'] !== 'admin') {
    SecurityLogger::log('UNAUTHORIZED_ACCESS', 'HIGH', 'Non-admin attempted to access user management', [
        'user_id' => $_SESSION['user_id'] ?? null,
        'username' => $_SESSION['username'] ?? 'anonymous',
        'role' => $_SESSION['role'] ?? 'none',
        'ip_address' => $_SERVER['REMOTE_ADDR'],
        'user_agent' => $_SERVER['HTTP_USER_AGENT']
    ]);
    redirect_to_dashboard();
}

// Log successful access to user management
SecurityLogger::log('USER_MANAGEMENT_ACCESS', 'LOW', 'Admin accessed user management system', [
    'user_id' => $_SESSION['user_id'],
    'username' => $_SESSION['username'],
    'role' => $_SESSION['role'],
    'ip_address' => $_SERVER['REMOTE_ADDR']
]);

// Get user statistics
$total_users_stmt = $pdo->query("SELECT COUNT(*) as total FROM users");
$total_users = $total_users_stmt->fetch()['total'];

$active_users_stmt = $pdo->query("SELECT COUNT(*) as total FROM cadet_profiles WHERE status = 'Active'");
$active_users = $active_users_stmt->fetch()['total'];

$recent_users_stmt = $pdo->query("SELECT COUNT(*) as total FROM users WHERE DATE(created_at) >= DATE_SUB(CURDATE(), INTERVAL 7 DAY)");
$recent_users = $recent_users_stmt->fetch()['total'];
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Management - ROTC Management System</title>
    <link rel="stylesheet" href="css/tactical-theme.css">
    <link rel="stylesheet" href="css/dashboard-unified.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <script src="js/dashboard-unified.js"></script>
</head>
<body data-role="admin">
    <div class="dashboard-container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <div class="sidebar-header">
                <div class="logo">
                    <div class="logo-icon"><i class="fas fa-shield-alt"></i></div>
                    <span>Admin Command Center</span>
                </div>
            </div>
            
            <nav class="sidebar-nav">
                <div class="nav-menu">
                    <!-- Navigation will be generated by JavaScript -->
                </div>
            </nav>
        </aside>

        <!-- Main Content -->
        <main class="main-content">
            <!-- Header -->
            <header class="header">
                <div class="header-left">
                    <button class="sidebar-toggle">
                        <i class="fas fa-bars"></i>
                    </button>
                    <h1 class="page-title">User Management</h1>
                </div>
                
                <div class="header-center">
                    <div class="search-container">
                        <i class="fas fa-search search-icon"></i>
                        <input type="text" placeholder="Search users..." class="search-input" id="userSearch">
                    </div>
                </div>
                
                <div class="header-right">
                    <div class="header-actions">
                        <button class="action-btn" title="Notifications">
                            <i class="fas fa-bell"></i>
                            <span class="badge">3</span>
                        </button>
                        <div class="user-menu">
                            <div class="user-avatar">
                                <i class="fas fa-user-shield"></i>
                                <span class="user-name"><?php echo htmlspecialchars($_SESSION['full_name']); ?></span>
                                <i class="fas fa-chevron-down"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <!-- Content -->
            <div class="content">
                <!-- Statistics Cards -->
                <div class="stats-grid">
                    <div class="stat-card">
                        <div class="stat-header">
                            <div class="stat-title">Total Users</div>
                            <div class="stat-icon" style="background: linear-gradient(135deg, #28a745 0%, #20c997 100%);">
                                <i class="fas fa-users"></i>
                            </div>
                        </div>
                        <div class="stat-value"><?php echo $total_users; ?></div>
                        <div class="stat-change positive">
                            <i class="fas fa-arrow-up"></i>
                            <span>All registered users</span>
                        </div>
                    </div>

                    <div class="stat-card">
                        <div class="stat-header">
                            <div class="stat-title">Active Users</div>
                            <div class="stat-icon" style="background: linear-gradient(135deg, #007bff 0%, #0056b3 100%);">
                                <i class="fas fa-user-check"></i>
                            </div>
                        </div>
                        <div class="stat-value"><?php echo $active_users; ?></div>
                        <div class="stat-change positive">
                            <i class="fas fa-check"></i>
                            <span>Currently active</span>
                        </div>
                    </div>

                    <div class="stat-card">
                        <div class="stat-header">
                            <div class="stat-title">New This Week</div>
                            <div class="stat-icon" style="background: linear-gradient(135deg, #6f42c1 0%, #5a2d91 100%);">
                                <i class="fas fa-user-plus"></i>
                            </div>
                        </div>
                        <div class="stat-value"><?php echo $recent_users; ?></div>
                        <div class="stat-change positive">
                            <i class="fas fa-calendar-week"></i>
                            <span>Last 7 days</span>
                        </div>
                    </div>
                </div>

                <!-- User Management Table -->
                <div class="content-card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="fas fa-users-cog"></i>
                            User Management
                        </h3>
                        <div class="card-actions">
                            <button class="btn btn-primary" onclick="window.location.href='registration.php'">
                                <i class="fas fa-user-plus"></i>
                                Add New User
                            </button>
                        </div>
                    </div>
                    <div class="card-content">
                        <div class="table-container">
                            <table class="data-table" id="usersTable">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Username</th>
                                        <th>Email</th>
                                        <th>Role</th>
                                        <th>Status</th>
                                        <th>Registration Date</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    $sql = "SELECT u.id, u.username, u.email, u.role, u.created_at, cp.status FROM users u LEFT JOIN cadet_profiles cp ON u.id = cp.user_id ORDER BY u.id ASC";
                                    $result = $pdo->query($sql);

                                    if ($result->rowCount() > 0) {
                                        while($row = $result->fetch()) {
                                            echo "<tr>";
                                            echo "<td>" . htmlspecialchars($row['id']) . "</td>";
                                            echo "<td>" . htmlspecialchars($row['username']) . "</td>";
                                            echo "<td>" . htmlspecialchars($row['email']) . "</td>";
                                            echo "<td><span class='role-badge role-" . strtolower($row['role']) . "'>" . htmlspecialchars(ucfirst($row['role'])) . "</span></td>";
                                            echo "<td><span class='status-badge status-" . strtolower($row['status'] ?? 'active') . "'>" . htmlspecialchars(ucfirst($row['status'] ?? 'Active')) . "</span></td>";
                                            echo "<td>" . date('M j, Y', strtotime($row['created_at'])) . "</td>";
                                            echo "<td class='action-buttons'>";
                                            echo "<a href='edit_user.php?id=" . $row['id'] . "' class='btn btn-sm btn-primary' title='Edit User'><i class='fas fa-edit'></i></a>";
                                            // Add a check to not show delete for the logged-in admin
                                            if ($row['id'] != $_SESSION['user_id']) {
                                                echo "<a href='delete_user.php?id=" . $row['id'] . "' class='btn btn-sm btn-danger' onclick='return confirm(\"Are you sure you want to delete this user?\");' title='Delete User'><i class='fas fa-trash'></i></a>";
                                            }
                                            echo "</td>";
                                            echo "</tr>";
                                        }
                                    } else {
                                        echo "<tr><td colspan='7' class='text-center'>No users found.</td></tr>";
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <style>
    .role-badge {
        padding: 4px 8px;
        border-radius: 12px;
        font-size: 0.75rem;
        font-weight: 600;
        text-transform: uppercase;
    }
    .role-admin { background: rgba(220, 53, 69, 0.1); color: #dc3545; }
    .role-instructor { background: rgba(40, 167, 69, 0.1); color: #28a745; }
    .role-officer { background: rgba(0, 123, 255, 0.1); color: #007bff; }
    .role-cadet { background: rgba(108, 117, 125, 0.1); color: #6c757d; }
    .role-1cl, .role-2cl { background: rgba(40, 167, 69, 0.1); color: #28a745; }
    .role-commandant { background: rgba(111, 66, 193, 0.1); color: #6f42c1; }
    
    .status-badge {
        padding: 4px 8px;
        border-radius: 12px;
        font-size: 0.75rem;
        font-weight: 600;
        text-transform: uppercase;
    }
    .status-active { background: rgba(40, 167, 69, 0.1); color: #28a745; }
    .status-inactive { background: rgba(220, 53, 69, 0.1); color: #dc3545; }
    .status-pending { background: rgba(40, 167, 69, 0.1); color: #28a745; }
    
    .action-buttons {
        display: flex;
        gap: 8px;
    }
    
    .action-buttons .btn {
        padding: 6px 10px;
    }
    </style>

    <script>
    // Search functionality
    document.getElementById('userSearch').addEventListener('input', function() {
        const searchTerm = this.value.toLowerCase();
        const tableRows = document.querySelectorAll('#usersTable tbody tr');
        
        tableRows.forEach(row => {
            const text = row.textContent.toLowerCase();
            row.style.display = text.includes(searchTerm) ? '' : 'none';
        });
    });
    </script>
</body>
</html>
