<?php
require_once 'includes/session.php';
require_once 'includes/db.php';

// Access control: Allow Admins, Instructors, and Officers
check_login();
if (!in_array($_SESSION['role'], ['admin', 'instructor', 'officer', '1cl', '2cl', 'commandant'])) {
    redirect_to_dashboard();
}

$profile_id = $_GET['id'] ?? null;
if (!$profile_id) {
    header("location: admin_dashboard.php");
    exit;
}

// Fetch profile data
$sql = "SELECT cp.*, u.username, u.email FROM cadet_profiles cp JOIN users u ON cp.user_id = u.id WHERE cp.id = ?";
if ($stmt = $link->prepare($sql)) {
    $stmt->bind_param("i", $profile_id);
    $stmt->execute();
    $result = $stmt->get_result();
    if ($result->num_rows == 1) {
        $profile = $result->fetch_assoc();
    } else {
        die('Profile not found.');
    }
    $stmt->close();
} else {
    die('Error fetching profile data.');
}

$page_title = 'View Cadet Profile';
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $page_title; ?> - ROTC Management System</title>
    <link rel="stylesheet" href="css/tactical-theme.css">
    <link rel="stylesheet" href="css/dashboard-unified.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>

<body data-role="<?php echo $_SESSION['role']; ?>">
    <div class="dashboard-container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <div class="sidebar-header">
                <div class="logo">
                    <div class="logo-icon"><i class="fas fa-user-circle"></i></div>
                    <span>Cadet Profile</span>
                </div>
            </div>
            
            <nav class="sidebar-nav">
                <div class="nav-menu">
                    <!-- Navigation will be generated by JavaScript -->
                </div>
            </nav>
        </aside>

        <!-- Main Content -->
        <main class="main-content">
            <!-- Header -->
            <header class="header">
                <div class="header-left">
                    <button class="sidebar-toggle">
                        <i class="fas fa-bars"></i>
                    </button>
                    <h1 class="page-title">Cadet Profile: <?php echo htmlspecialchars($profile['first_name'] . ' ' . $profile['last_name']); ?></h1>
                </div>
                
                <div class="header-right">
                    <div class="header-actions">
                        <button class="action-btn" onclick="window.print()" title="Print Profile">
                            <i class="fas fa-print"></i>
                        </button>
                        <div class="user-menu">
                            <div class="user-avatar">
                                <i class="fas fa-user"></i>
                                <span class="user-name"><?php echo htmlspecialchars($_SESSION['full_name']); ?></span>
                                <i class="fas fa-chevron-down"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <!-- Content Area -->
            <div class="content-area">
                <!-- Profile Header -->
                <div class="profile-header">
                    <div class="profile-photo">
                        <?php if (!empty($profile['photo_path']) && file_exists('uploads/photos/' . $profile['photo_path'])): ?>
                            <img src="uploads/photos/<?php echo htmlspecialchars($profile['photo_path']); ?>" alt="Cadet Photo" class="profile-image">
                        <?php else: ?>
                            <div class="profile-placeholder">
                                <i class="fas fa-user"></i>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div class="profile-info">
                        <h2><?php echo htmlspecialchars($profile['first_name'] . ' ' . $profile['last_name']); ?></h2>
                        <p class="profile-subtitle"><?php echo htmlspecialchars($profile['student_id'] ?? 'N/A'); ?> • <?php echo htmlspecialchars($profile['platoon'] ?? 'N/A'); ?> Platoon</p>
                        <div class="profile-badges">
                            <span class="badge badge-primary"><?php echo htmlspecialchars($profile['year_level'] ?? 'N/A'); ?></span>
                            <span class="badge badge-secondary"><?php echo htmlspecialchars($profile['course'] ?? 'N/A'); ?></span>
                        </div>
                    </div>
                    <div class="profile-actions">
                        <?php if (in_array($_SESSION['role'], ['admin', 'instructor'])): ?>
                            <button class="btn btn-primary" onclick="window.location.href='generate_id.php?id=<?php echo $profile['id']; ?>'">
                                <i class="fas fa-id-card"></i> Generate ID
                            </button>
                        <?php endif; ?>
                        <button class="btn btn-outline" onclick="goBack()">
                            <i class="fas fa-arrow-left"></i> Back
                        </button>
                    </div>
                </div>

                <!-- Profile Details -->
                <div class="profile-content">
                    <div class="profile-grid">
                        <!-- Personal Information -->
                        <div class="content-card">
                            <div class="card-header">
                                <h3><i class="fas fa-user"></i> Personal Information</h3>
                            </div>
                            <div class="card-content">
                                <div class="info-grid">
                                    <div class="info-item">
                                        <label>Full Name</label>
                                        <span><?php echo htmlspecialchars($profile['first_name'] . ' ' . $profile['last_name']); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>Email</label>
                                        <span><?php echo htmlspecialchars($profile['email']); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>Contact Number</label>
                                        <span><?php echo htmlspecialchars($profile['contact_number'] ?? 'N/A'); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>Date of Birth</label>
                                        <span><?php echo htmlspecialchars($profile['date_of_birth'] ?? 'N/A'); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>Age</label>
                                        <span><?php echo htmlspecialchars($profile['age'] ?? 'N/A'); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>Address</label>
                                        <span><?php echo htmlspecialchars($profile['address'] ?? 'N/A'); ?></span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Academic Information -->
                        <div class="content-card">
                            <div class="card-header">
                                <h3><i class="fas fa-graduation-cap"></i> Academic Information</h3>
                            </div>
                            <div class="card-content">
                                <div class="info-grid">
                                    <div class="info-item">
                                        <label>Student ID</label>
                                        <span><?php echo htmlspecialchars($profile['student_id'] ?? 'N/A'); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>School</label>
                                        <span><?php echo htmlspecialchars($profile['school'] ?? 'N/A'); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>Course</label>
                                        <span><?php echo htmlspecialchars($profile['course'] ?? 'N/A'); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>Year Level</label>
                                        <span><?php echo htmlspecialchars($profile['year_level'] ?? 'N/A'); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>Platoon</label>
                                        <span><?php echo htmlspecialchars($profile['platoon'] ?? 'N/A'); ?></span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Physical Information -->
                        <div class="content-card">
                            <div class="card-header">
                                <h3><i class="fas fa-dumbbell"></i> Physical Information</h3>
                            </div>
                            <div class="card-content">
                                <div class="info-grid">
                                    <div class="info-item">
                                        <label>Height</label>
                                        <span><?php echo htmlspecialchars($profile['height'] ?? 'N/A'); ?> cm</span>
                                    </div>
                                    <div class="info-item">
                                        <label>Weight</label>
                                        <span><?php echo htmlspecialchars($profile['weight'] ?? 'N/A'); ?> kg</span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Emergency Contact -->
                        <div class="content-card">
                            <div class="card-header">
                                <h3><i class="fas fa-phone"></i> Emergency Contact</h3>
                            </div>
                            <div class="card-content">
                                <div class="info-grid">
                                    <div class="info-item">
                                        <label>Contact Name</label>
                                        <span><?php echo htmlspecialchars($profile['emergency_contact_name'] ?? 'N/A'); ?></span>
                                    </div>
                                    <div class="info-item">
                                        <label>Contact Number</label>
                                        <span><?php echo htmlspecialchars($profile['emergency_contact_number'] ?? 'N/A'); ?></span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- QR Code -->
                        <div class="content-card">
                            <div class="card-header">
                                <h3><i class="fas fa-qrcode"></i> QR Code</h3>
                            </div>
                            <div class="card-content">
                                <div class="qr-container">
                                    <?php if (!empty($profile['qr_code_path']) && file_exists($profile['qr_code_path'])): ?>
                                        <img src="<?php echo htmlspecialchars($profile['qr_code_path']); ?>" alt="QR Code" class="qr-image">
                                    <?php else: ?>
                                        <div class="qr-placeholder">
                                            <i class="fas fa-qrcode"></i>
                                            <p>QR Code not yet generated</p>
                                            <?php if (in_array($_SESSION['role'], ['admin', 'instructor'])): ?>
                                                <button class="btn btn-primary btn-sm" onclick="generateQR(<?php echo $profile['id']; ?>)">
                                                    Generate QR Code
                                                </button>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <script src="js/dashboard-unified.js"></script>
    <script>
        function goBack() {
            if (document.referrer) {
                window.history.back();
            } else {
                window.location.href = 'my_platoons.php';
            }
        }

        function generateQR(profileId) {
            window.location.href = `generate_qr.php?id=${profileId}`;
        }
    </script>

    <style>
        .profile-header {
            display: flex;
            align-items: center;
            gap: 2rem;
            padding: 2rem;
            background: var(--card-bg);
            border-radius: 12px;
            margin-bottom: 2rem;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }

        .profile-photo {
            flex-shrink: 0;
        }

        .profile-image {
            width: 120px;
            height: 120px;
            border-radius: 50%;
            object-fit: cover;
            border: 4px solid var(--primary);
        }

        .profile-placeholder {
            width: 120px;
            height: 120px;
            border-radius: 50%;
            background: var(--background-secondary);
            display: flex;
            align-items: center;
            justify-content: center;
            border: 4px solid var(--border-color);
        }

        .profile-placeholder i {
            font-size: 3rem;
            color: var(--text-muted);
        }

        .profile-info {
            flex: 1;
        }

        .profile-info h2 {
            margin: 0 0 0.5rem 0;
            color: var(--text-primary);
        }

        .profile-subtitle {
            color: var(--text-secondary);
            margin: 0 0 1rem 0;
        }

        .profile-badges {
            display: flex;
            gap: 0.5rem;
        }

        .badge {
            padding: 0.25rem 0.75rem;
            border-radius: 20px;
            font-size: 0.8rem;
            font-weight: 500;
        }

        .badge-primary {
            background: var(--primary);
            color: white;
        }

        .badge-secondary {
            background: var(--success);
            color: white;
        }

        .profile-actions {
            display: flex;
            flex-direction: column;
            gap: 0.5rem;
        }

        .profile-content {
            margin-top: 2rem;
        }

        .profile-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
            gap: 1.5rem;
        }

        .info-grid {
            display: grid;
            gap: 1rem;
        }

        .info-item {
            display: flex;
            flex-direction: column;
            gap: 0.25rem;
        }

        .info-item label {
            font-weight: 600;
            color: var(--text-secondary);
            font-size: 0.9rem;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        .info-item span {
            color: var(--text-primary);
            font-size: 1rem;
        }

        .qr-container {
            text-align: center;
        }

        .qr-image {
            max-width: 200px;
            height: auto;
        }

        .qr-placeholder {
            padding: 2rem;
            color: var(--text-muted);
        }

        .qr-placeholder i {
            font-size: 3rem;
            margin-bottom: 1rem;
        }

        @media (max-width: 768px) {
            .profile-header {
                flex-direction: column;
                text-align: center;
            }
            
            .profile-grid {
                grid-template-columns: 1fr;
            }
        }
    </style>
</body>
</html>
