display_errors=Off
log_errors=On
expose_php=Off

session.save_path=/tmp
session.use_strict_mode=1
session.cookie_httponly=1
session.cookie_samesite=Lax

upload_tmp_dir=/tmp
sys_temp_dir=/tmp

opcache.enable=1
opcache.validate_timestamps=0
